// ============================================================
// js/books-catalog.js — Kitoblar katalogi metadata (Client-Side)
// ============================================================
// Faqat kitob metama'lumotlari. Savollar va javoblar YO'Q.
// ============================================================
export const books = [
  {
    "id": "otkan-kunlar",
    "title": "O'tkan kunlar",
    "author": "Abdulla Qodiriy",
    "year": 1925,
    "pages": 380,
    "genre": "Tarixiy Roman",
    "difficulty": "advanced",
    "cover": "covers/otkan-kunlar.jpg",
    "coverBg": "linear-gradient(135deg, #2E1A47, #4F1D7C)",
    "coverTitleColor": "#F59E0B",
    "coverImage": "covers/otkan-kunlar.jpg",
    "description": "O'zbek adabiyotidagi ilk roman. Otabek va Kumushning fojiali sevgisi fonida Qo'qon xonligi davridagi xalq hayoti va taxt mojarolari tasvirlanadi.",
    "questionCount": 10
  },
  {
    "id": "mehrobdan-chayon",
    "title": "Mehrobdan chayon",
    "author": "Abdulla Qodiriy",
    "year": 1928,
    "pages": 320,
    "genre": "Tarixiy Roman",
    "difficulty": "advanced",
    "cover": "covers/mehrobdan-chayon.jpg",
    "coverBg": "linear-gradient(135deg, #1E3A8A, #3B82F6)",
    "coverTitleColor": "#E0F2FE",
    "coverImage": "covers/mehrobdan-chayon.jpg",
    "description": "Xonliklar davridagi saroy mojarolari va oddiy xalq hayoti, shuningdek, Anvar va Ra'noning pokiza sevgisi haqida hikoya qiluvchi mashhur asar.",
    "questionCount": 10
  },
  {
    "id": "kecha-va-kunduz",
    "title": "Kecha va kunduz",
    "author": "Abdulhamid Cho'lpon",
    "year": 1936,
    "pages": 340,
    "genre": "Roman",
    "difficulty": "advanced",
    "cover": "covers/kecha-va-kunduz.jpg",
    "coverBg": "linear-gradient(135deg, #311042, #581C87)",
    "coverTitleColor": "#F3E8FF",
    "coverImage": "covers/kecha-va-kunduz.jpg",
    "description": "Mustamlaka davri o'zbek jamiyatining og'ir ijtimoiy-siyosiy ahvoli, jaholat botqog'i hamda Zebi taqdiri orqali ifodalangan roman.",
    "questionCount": 10
  },
  {
    "id": "sarob",
    "title": "Sarob",
    "author": "Abdulla Qahhor",
    "year": 1937,
    "pages": 310,
    "genre": "Psixologik Roman",
    "difficulty": "advanced",
    "cover": "covers/sarob.jpg",
    "coverBg": "linear-gradient(135deg, #7F1D1D, #B91C1C)",
    "coverTitleColor": "#FEE2E2",
    "coverImage": "covers/sarob.jpg",
    "description": "Saidiy obrazi orqali milliy ziyolilarning sovet mafkurasi ta'sirida sarobga aylangan hayotiy g'oyalari va fojialari yoritilgan asar.",
    "questionCount": 10
  },
  {
    "id": "shum-bola",
    "title": "Shum bola",
    "author": "G'afur G'ulom",
    "year": 1936,
    "pages": 180,
    "genre": "Qissa / Satira",
    "difficulty": "beginner",
    "cover": "covers/shum-bola.jpg",
    "coverBg": "linear-gradient(135deg, #065F46, #059669)",
    "coverTitleColor": "#D1FAE5",
    "coverImage": "covers/shum-bola.jpg",
    "description": "Toshkentlik bir bolakayning sarguzashtlari, uning topqirligi va hayotiy qiyinchiliklarni kulgi yordamida yengib o'tishi tasvirlangan asar.",
    "questionCount": 10
  },
  {
    "id": "qorqma",
    "title": "Qo'rqma",
    "author": "Javlon Jovliyev",
    "year": 2020,
    "pages": 380,
    "genre": "Zamonaviy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #991B1B, #450A0A)",
    "coverTitleColor": "#FEE2E2",
    "coverImage": "https://cdn-minio.mutolaa.com/media/books/2024/11/Javlon_Jovliyev._Qorqma.jpg",
    "description": "1920-yillarda Germaniyaga o'qishga ketgan va sovet mustabid tuzumi qurboniga aylangan jadid talabalarning taqdiri haqidagi mashhur asar.",
    "questionCount": 10
  },
  {
    "id": "halqa",
    "title": "Halqa",
    "author": "Akrom Malik",
    "year": 2019,
    "pages": 280,
    "genre": "Falsafiy Qissa",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #475569, #334155)",
    "coverTitleColor": "#F1F5F9",
    "coverImage": "https://kitobxon.com/img_knigi/7935.jpg",
    "description": "Inson ruhiyatining chuqur iztiroblari, dunyo havoyi nafsining tuzoqlari va qalb ozodligiga erishish yo'lidagi ruhiy zanjirlarni uzish falsafasi.",
    "questionCount": 10
  },
  {
    "id": "javob",
    "title": "Javob",
    "author": "Akrom Malik",
    "year": 2021,
    "pages": 260,
    "genre": "Falsafiy Qissa",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0F766E, #134E4A)",
    "coverTitleColor": "#CCFBF1",
    "coverImage": "https://images.unsplash.com/photo-1532012164546-f432f2e3edd7?w=600&auto=format&fit=crop&q=80",
    "description": "'Halqa' asarining mantiqiy davomi bo'lib, unda inson vijdoni, tavba va ma'naviy najot yo'lidagi savollarga teran javoblar izlanadi.",
    "questionCount": 10
  },
  {
    "id": "dard",
    "title": "Dard",
    "author": "Akrom Malik",
    "year": 2022,
    "pages": 240,
    "genre": "Psixologik Qissa",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #7C2D12, #431407)",
    "coverTitleColor": "#FFEDD5",
    "coverImage": "https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80",
    "description": "Insoniy dard, ruhiy jarohatlar va ularning shifo topishi, qalbning Yaratganga bo'lgan muhabbati orqali komillikka yetish yo'li.",
    "questionCount": 10
  },
  {
    "id": "shamol-ortidan-yugurib",
    "title": "Shamol ortidan yugurib",
    "author": "Xolid Husayniy",
    "year": 2003,
    "pages": 400,
    "genre": "Dramatik Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #854D0E, #422006)",
    "coverTitleColor": "#FEF9C3",
    "coverImage": "https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=600&auto=format&fit=crop&q=80",
    "description": "Afg'onistondagi urush fojialari, do'stlik, xiyonat va kechikkan pushaymonlikning vijdondagi abadiy iztirobi haqidagi jahon miqyosidagi buyuk asar.",
    "questionCount": 10
  },
  {
    "id": "ming-quyosh-shulasi",
    "title": "Ming quyosh shu'lasi",
    "author": "Xolid Husayniy",
    "year": 2007,
    "pages": 420,
    "genre": "Dramatik Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #B45309, #78350F)",
    "coverTitleColor": "#FEF3C7",
    "coverImage": "https://images.unsplash.com/photo-1499209974431-9dddcece7f88?w=600&auto=format&fit=crop&q=80",
    "description": "Ikki afg'on ayoli — Maryam va Layloning fojeali, ammo matonatli qismati, shafqatsiz jamiyatda ayol sha'ni va buyuk qurbonlik hikoyasi.",
    "questionCount": 10
  },
  {
    "id": "dengiz-sadosi",
    "title": "Dengiz sadosi",
    "author": "Xolid Husayniy",
    "year": 2013,
    "pages": 380,
    "genre": "Roman",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0369A1, #082F49)",
    "coverTitleColor": "#E0F2FE",
    "coverImage": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
    "description": "Ayriliq, oilaviy mehr va avlodlar o'rtasidagi uzilmas rishtalar haqidagi to'lqinlantiruvchi ko'p tarmoqli roman.",
    "questionCount": 10
  },
  {
    "id": "atom-odatlar",
    "title": "Atom odatlar",
    "author": "Jeyms Klir",
    "year": 2018,
    "pages": 320,
    "genre": "Shaxsiy Rivojlanish",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #F59E0B, #EA580C)",
    "coverTitleColor": "#FFFBEB",
    "coverImage": "https://cdn-minio.mutolaa.com/media/books/2024/11/Jeyms_Klir._Atom_odatlar.jpg",
    "description": "Kichik o'zgarishlarning ulkan natijasi. Yomon odatlardan qutulish va foydali tizimlarni shakllantirish bo'yicha global bestseller.",
    "questionCount": 10
  },
  {
    "id": "sapiens",
    "title": "Sapiens: Insoniyatning qisqacha tarixi",
    "author": "Yuval Noy Harari",
    "year": 2014,
    "pages": 512,
    "genre": "Ilmiy-Ommabop",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #475569, #1E293B)",
    "coverTitleColor": "#F1F5F9",
    "coverImage": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
    "description": "Ong inqilobi, qishloq xo'jaligi va fan-texnika taraqqiyoti orqali insoniyatning qanday qilib Yer yuzining hukmron turiga aylangani tahlili.",
    "questionCount": 10
  },
  {
    "id": "pul-psixologiyasi",
    "title": "Pul psixologiyasi",
    "author": "Morgan Xyuzel",
    "year": 2020,
    "pages": 280,
    "genre": "Moliya / Psixologiya",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #047857, #064E3B)",
    "coverTitleColor": "#D1FAE5",
    "coverImage": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=600&auto=format&fit=crop&q=80",
    "description": "Boylik va moliyaviy erkinlik bilimdan ko'ra ko'proq insonning xulq-atvori, sabr-toqati va qarorlariga bog'liqligini isbotlovchi bestseller.",
    "questionCount": 10
  },
  {
    "id": "ikigai",
    "title": "Ikigai: Uzoq va baxtli hayotning yapon siri",
    "author": "Ektor Garsiya, Franchesk Miralles",
    "year": 2016,
    "pages": 200,
    "genre": "Falsafa / Salomatlik",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #BE123C, #881337)",
    "coverTitleColor": "#FFE4E6",
    "coverImage": "https://images.unsplash.com/photo-1528164344705-475426879c0d?w=600&auto=format&fit=crop&q=80",
    "description": "Har bir insonning o'z hayotiy maqsadini topishi, xotirjamlik, to'g'ri ovqatlanish va uzoq umr ko'rishning yaponcha falsafasi.",
    "questionCount": 10
  },
  {
    "id": "farengeyt-451",
    "title": "Farengeyt bo'yicha 451 daraja",
    "author": "Rey Bredberi",
    "year": 1953,
    "pages": 250,
    "genre": "Distopiya",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #C2410C, #7C2D12)",
    "coverTitleColor": "#FFEDD5",
    "coverImage": "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=600&auto=format&fit=crop&q=80",
    "description": "Kitob o'qish qat'iyan taqiqlangan va kitoblar yoqib yuboriladigan kelajak jamiyatida o't o'chiruvchi Gay Montegning uyg'onish fojiasi.",
    "questionCount": 10
  },
  {
    "id": "choliqushi",
    "title": "Choliqushi",
    "author": "Reshat Nuri Guntekin",
    "year": 1922,
    "pages": 450,
    "genre": "Klassik Roman",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #4338CA, #312E81)",
    "coverTitleColor": "#E0E7FF",
    "coverImage": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&auto=format&fit=crop&q=80",
    "description": "Faridaning qishloqma-qishloq kezib ma'rifat ulashishi, mag'rur qalb iztiroblari va Komronga bo'lgan samimiy muhabbati tasvirlangan o'lmas asar.",
    "questionCount": 10
  },
  {
    "id": "ichimizdagi-shayton",
    "title": "Ichimizdagi shayton",
    "author": "Sabohiddin Ali",
    "year": 1940,
    "pages": 270,
    "genre": "Psixologik Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #374151, #1F2937)",
    "coverTitleColor": "#F9FAFB",
    "coverImage": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
    "description": "Inson o'z irodasizliklari, zaifliklari va xatolarini 'ichimdagi shayton majbur qildi' deb oqlashining psixologik fosh etilishi.",
    "questionCount": 10
  },
  {
    "id": "mork-postinli-madonna",
    "title": "Mo'rk po'stinli Madonna",
    "author": "Sabohiddin Ali",
    "year": 1943,
    "pages": 220,
    "genre": "Lirik Roman",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #9D174D, #70073B)",
    "coverTitleColor": "#FCE7F3",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    "description": "Raif afandining qalbida butun umr saqlangan sirli portret va Mariya Puderga bo'lgan cheksiz, ammo fojiali sevgisi hikoyasi.",
    "questionCount": 10
  },
  {
    "id": "orwell-1984",
    "title": "1984",
    "author": "Jorj Oruell",
    "year": 1949,
    "pages": 328,
    "genre": "Distopiya",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E293B, #0F172A)",
    "coverTitleColor": "#FFFFFF",
    "coverImage": "https://cdn-minio.mutolaa.com/media/books/2024/11/1-book.jpg",
    "description": "Katta Og'a nazorati, Haqiqat vazirligi, ongli manipulyatsiya va insoniy tuyg'ularning totalitar tizim tomonidan poymol qilinishi.",
    "questionCount": 10
  },
  {
    "id": "molxona",
    "title": "Molxona (Hayvonlar xo'jaligi)",
    "author": "Jorj Oruell",
    "year": 1945,
    "pages": 140,
    "genre": "Satirik Allegoriya",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0284C7, #0369A1)",
    "coverTitleColor": "#F0F9FF",
    "coverImage": "https://cdn-minio.mutolaa.com/media/books/2024/11/molxona.jpg",
    "description": "Fermadagi hayvonlarning mustaqillik uchun kurashlari, so'ngra hokimiyat tepasiga kelgan to'ng'izlar diktaturasining paydo bo'lishi.",
    "questionCount": 10
  },
  {
    "id": "alkimyogar",
    "title": "Alkimyogar",
    "author": "Paulo Koelo",
    "year": 1988,
    "pages": 220,
    "genre": "Falsafiy Roman",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #D97706, #78350F)",
    "coverTitleColor": "#FEF3C7",
    "coverImage": "https://cdn-minio.mutolaa.com/media/books/2024/02/IMG_20240201_135352_148.png",
    "description": "Cho'pon yigit Santyagoning Misr ehromlaridagi o'z orzusi va xazinasini qidirib yo'lga chiqishi, yo'ldagi hayotiy va ruhiy saboqlar.",
    "questionCount": 10
  },
  {
    "id": "kichkina-shohzoda",
    "title": "Kichkina shohzoda",
    "author": "Antuan de Sent-Ekzyuperi",
    "year": 1943,
    "pages": 120,
    "genre": "Falsafiy Ertak",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E3A8A, #6366F1)",
    "coverTitleColor": "#EFF6FF",
    "coverImage": "https://images.uzum.uz/d3rn9j8s9rfdsl9e0m4g/original.jpg",
    "description": "Yurak bilan ko'riladigan haqiqat, atirgulga bo'lgan mas'uliyat va kattalar yo'qotgan qalb sofligi haqidagi abadiy asar.",
    "questionCount": 10
  },
  {
    "id": "jinoyat-va-jazo",
    "title": "Jinoyat va jazo",
    "author": "Fyodor Dostoevskiy",
    "year": 1866,
    "pages": 600,
    "genre": "Psixologik Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #451A03, #78350F)",
    "coverTitleColor": "#FEF3C7",
    "coverImage": "https://images.uzum.uz/d383tvfiub30vbrv0efg/original.jpg",
    "description": "Raskolnikovning intellektual nazariyasi, kampirning o'ldirilishi va vijdoni oldidagi dahshatli ruhiy qiynoqlar hamda iymon orqali najot topishi.",
    "questionCount": 10
  },
  {
    "id": "aka-uka-karamazovlar",
    "title": "Aka-uka Karamazovlar",
    "author": "Fyodor Dostoevskiy",
    "year": 1880,
    "pages": 850,
    "genre": "Falsafiy Epopeya",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #3B0764, #1E1B4B)",
    "coverTitleColor": "#FAF5FF",
    "coverImage": "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&auto=format&fit=crop&q=80",
    "description": "Inson qalbidagi ezgulik va yovuzlik kurashi, Xudo va erkin iroda, 'Buyuk Inkvizitor' afsonasi orqali insoniyat taqdiri tahlili.",
    "questionCount": 10
  },
  {
    "id": "evrilish",
    "title": "Evrilish (Metamorphosis)",
    "author": "Frans Kafka",
    "year": 1915,
    "pages": 110,
    "genre": "Ekzistensial Qissa",
    "difficulty": "advanced",
    "cover": "covers/evrilish.jpg",
    "coverBg": "linear-gradient(135deg, #0D9488, #0284C7)",
    "coverTitleColor": "#F4F4F5",
    "coverImage": "covers/evrilish.jpg",
    "description": "\"Evrilish\" — bir kuni ertalab ulkan hasharotga aylanib uyg'ongan Gregor Zamza haqidagi falsafiy qissa. Asar insonning jamiyat va o'z oilasi davrasida mutlaqo yolg'izlanib, begonalashib qolishini ko'rsatadi. Muallif moddiy manfaat ustiga qurilgan munosabatlarning soxtaligini absurd va fojiaviy tarzda ochib bergan.",
    "questionCount": 10
  },
  {
    "id": "begona",
    "title": "Begona (L'Étranger)",
    "author": "Alber Kamyu",
    "year": 1942,
    "pages": 160,
    "genre": "Ekzistensial Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #B45309, #78350F)",
    "coverTitleColor": "#FEF3C7",
    "coverImage": "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&auto=format&fit=crop&q=80",
    "description": "Merso obrazining soxta ijtimoiy qoidalarga bo'ysunmasligi, hayotning bema'niligi (absurd) va mutlaq rostgo'ylikning fojiasi.",
    "questionCount": 10
  },
  {
    "id": "baxtiyor-oila",
    "title": "Baxtiyor oila",
    "author": "Shayx Muhammad Sodiq Muhammad Yusuf",
    "year": 2011,
    "pages": 496,
    "genre": "Ma'naviy-Ma'rifiy",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #065F46, #022C22)",
    "coverTitleColor": "#ECFDF5",
    "coverImage": "https://images.unsplash.com/photo-1511895426328-dc8714191300?w=600&auto=format&fit=crop&q=80",
    "description": "Oila qurish, er-xotin burchlari, farzand tarbiyasi va mustahkam, totuv xonadon poydevorini qurish bo'yicha eng mashhur milliy qo'llanma.",
    "questionCount": 10
  },
  {
    "id": "ruhiy-tarbiya",
    "title": "Ruhiy tarbiya",
    "author": "Shayx Muhammad Sodiq Muhammad Yusuf",
    "year": 2008,
    "pages": 450,
    "genre": "Axloqiy / Tasavvuf",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E1B4B, #4C1D95)",
    "coverTitleColor": "#FAF5FF",
    "coverImage": "https://telegra.ph/file/e2a7fe152299b8602c7c7.jpg",
    "description": "Qalblarni poklash, ruh tarbiyasi va ijtimoiy hayot odoblari haqidagi chuqur falsafiy va diniy asar.",
    "questionCount": 10
  },
  {
    "id": "saodat-asri",
    "title": "Saodat asri qissalari",
    "author": "Ahmad Lutfiy Qozonchi",
    "year": 1995,
    "pages": 960,
    "genre": "Tarixiy-Diniy",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0D9488, #0F766E)",
    "coverTitleColor": "#CCFBF1",
    "coverImage": "https://assets.asaxiy.uz/product/items/desktop/b3259103ea5af737f73d7f9bfc2ce7712025032814141011250eRkZFNL6PK.jpg",
    "description": "Islom olami tarixi va Muhammad alayhissalom hayot yo'llarining nihoyatda jonli, ta'sirli va chiroyli tilda yozilgan badiiy qissalari.",
    "questionCount": 10
  },
  {
    "id": "halol-luqma",
    "title": "Halol luqma",
    "author": "Rauf Jilasun",
    "year": 2005,
    "pages": 210,
    "genre": "Ijtimoiy Qissa",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0F766E, #115E59)",
    "coverTitleColor": "#F0FDFA",
    "coverImage": "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600&auto=format&fit=crop&q=80",
    "description": "Halol mehnat, ota-ona tarbiyasi va halol luqmaning inson kelajagi va farzandlar axloqiga ko'rsatadigan beqiyos ta'siri.",
    "questionCount": 10
  },
  {
    "id": "shaytanat",
    "title": "Shaytanat",
    "author": "Tohir Malik",
    "year": 1994,
    "pages": 820,
    "genre": "Detektiv / Psixologik",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E1B4B, #0F172A)",
    "coverTitleColor": "#FFFFFF",
    "coverImage": "https://asarlar-assets-prod.s3.eu-north-1.amazonaws.com/covers/thumb/shaytanat-3-kitob_69b2a1458114b_1773314373.webp",
    "description": "O'zbek mafiya olami, jinoyatchilar qismati, insoniy burch hamda qonun ustuvorligi to'qnashuvi haqidagi eng mashhur o'zbek detektivi.",
    "questionCount": 10
  },
  {
    "id": "asrga-tatigulik-kun",
    "title": "Asrga tatigulik kun",
    "author": "Chingiz Aytmatov",
    "year": 1980,
    "pages": 420,
    "genre": "Falsafiy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #854D0E, #422006)",
    "coverTitleColor": "#FEF9C3",
    "coverImage": "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=600&auto=format&fit=crop&q=80",
    "description": "Edigeyning do'stini dafn qilish safari, Nayman ona fojiasi va o'z o'tmishi va xotirasidan ayrilgan 'mankurt'lik ramzi.",
    "questionCount": 10
  },
  {
    "id": "jamila",
    "title": "Jamila",
    "author": "Chingiz Aytmatov",
    "year": 1958,
    "pages": 120,
    "genre": "Lirik Qissa",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #15803D, #166534)",
    "coverTitleColor": "#DCFCE7",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    "description": "Urush yillaridagi og'ir qishloq hayoti, Daniyor va Jamilaning cheksiz samimiy va erkin sevgisi (Lui Aragon tomonidan 'dunyodagi eng go'zal sevgi qissasi' deb atalgan).",
    "questionCount": 10
  },
  {
    "id": "oq-kema",
    "title": "Oq kema",
    "author": "Chingiz Aytmatov",
    "year": 1970,
    "pages": 180,
    "genre": "Falsafiy Qissa",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0EA5E9, #0284C7)",
    "coverTitleColor": "#E0F2FE",
    "coverImage": "https://assets.asaxiy.uz/product/items/desktop/6f3ef77ac0e3619e98159e9b6febf5572022081214570385636K4jl5QGIA6.jpg.webp",
    "description": "Issiqko'l sohilidagi kichik bolakayning afsonaviy shoxdor ona bug'uga bo'lgan ishonchi va kattalarning vahshiyligi to'qnashuvi.",
    "questionCount": 10
  },
  {
    "id": "otamdan-qolgan-dalalar",
    "title": "Otamdan qolgan dalalar",
    "author": "Tog'ay Murod",
    "year": 1993,
    "pages": 290,
    "genre": "Milliy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #78350F, #451A03)",
    "coverTitleColor": "#FDF6E2",
    "coverImage": "https://qamar.uz/_next/image?url=%2Fmedia%2F1c%2FНоменклатура%2F20260724%2FOtamdan%20qolgan%20dalalar.jpg&w=1920&q=75",
    "description": "Dehqonchilik qismati, o'zbek dehqonlarining paxta yakkahokimligi davridagi dardu alamli, fojiali hayoti badiiy ifodasi.",
    "questionCount": 10
  },
  {
    "id": "yulduzli-tunlar",
    "title": "Yulduzli tunlar",
    "author": "Pirimqul Qodirov",
    "year": 1978,
    "pages": 520,
    "genre": "Tarixiy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #172554, #1D4ED8)",
    "coverTitleColor": "#DBEAFE",
    "coverImage": "",
    "description": "Zahiriddin Muhammad Boburning murakkab hayot yo'li, Vatan sog'inchi va Temuriylar saltanatining inqirozi aks etgan tarixiy roman.",
    "questionCount": 10
  },
  {
    "id": "ulugbek-xazinasi",
    "title": "Ulug'bek xazinasi",
    "author": "Odil Yoqubov",
    "year": 1973,
    "pages": 360,
    "genre": "Tarixiy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #854D0E, #CA8A04)",
    "coverTitleColor": "#FEF9C3",
    "coverImage": "",
    "description": "Buyuk astronom va hukmdor Mirzo Ulug'bek hayoti, ilm va jaholat o'rtasidagi shafqatsiz kurash, otalar va bolalar fojiasi.",
    "questionCount": 10
  },
  {
    "id": "ikki-eshik-orasi",
    "title": "Ikki eshik orasi",
    "author": "O'tkir Hoshimov",
    "year": 1986,
    "pages": 540,
    "genre": "Roman",
    "difficulty": "intermediate",
    "cover": "covers/ikki-eshik-orasi.png",
    "coverBg": "linear-gradient(135deg, #1E293B, #334155)",
    "coverTitleColor": "#F1F5F9",
    "coverImage": "covers/ikki-eshik-orasi.png",
    "description": "Urush va urushdan keyingi yillarda o'zbek xalqining boshidan kechirgan mashaqqatlari bir qancha taqdirlar misolida ko'rsatiladi.",
    "questionCount": 10
  },
  {
    "id": "dunyoning-ishlari",
    "title": "Dunyoning ishlari",
    "author": "O'tkir Hoshimov",
    "year": 1982,
    "pages": 230,
    "genre": "Qissalar to'plami",
    "difficulty": "beginner",
    "cover": "covers/dunyoning-ishlari.jpg",
    "coverBg": "linear-gradient(135deg, #78350F, #B45309)",
    "coverTitleColor": "#FEF3C7",
    "coverImage": "covers/dunyoning-ishlari.jpg",
    "description": "Muallifning o'z onasiga bag'ishlangan, har bir bobida onalik mehrining beqiyos qudrati aks etgan nihoyatda ta'sirli asari.",
    "questionCount": 10
  },
  {
    "id": "bahor-qaytmaydi",
    "title": "Bahor qaytmaydi",
    "author": "O'tkir Hoshimov",
    "year": 1970,
    "pages": 160,
    "genre": "Lirik Qissa",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #059669, #047857)",
    "coverTitleColor": "#ECFDF5",
    "coverImage": "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&auto=format&fit=crop&q=80",
    "description": "Yoshlikning beg'ubor orzulari, xatolar, kech anglangan muhabbat va orqaga qaytmas umr bahori haqidagi samimiy qissa.",
    "questionCount": 10
  },
  {
    "id": "tushda-kechgan-umrlar",
    "title": "Tushda kechgan umrlar",
    "author": "O'tkir Hoshimov",
    "year": 1993,
    "pages": 320,
    "genre": "Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #374151, #1F2937)",
    "coverTitleColor": "#F9FAFB",
    "coverImage": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80",
    "description": "Afg'on urushi qatnashchisi Rustamning fojiali qismati, qatag'on yillari va mustabid tuzum sindirgan insonlar taqdiri.",
    "questionCount": 10
  },
  {
    "id": "ufq",
    "title": "Ufq (Trilogiya)",
    "author": "Said Ahmad",
    "year": 1974,
    "pages": 680,
    "genre": "Epik Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #CA8A04, #854D0E)",
    "coverTitleColor": "#FEF9C3",
    "coverImage": "",
    "description": "Ikkinchi jahon urushi davridagi o'zbek oilalarining mardonavorligi, mehnat fronti va taqdirlarning murakkab burilishlari.",
    "questionCount": 10
  },
  {
    "id": "jimjitlik",
    "title": "Jimjitlik",
    "author": "Said Ahmad",
    "year": 1988,
    "pages": 350,
    "genre": "Ijtimoiy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E293B, #0F172A)",
    "coverTitleColor": "#F8FAFC",
    "coverImage": "https://images.unsplash.com/photo-1495640388908-05fa85288e61?w=600&auto=format&fit=crop&q=80",
    "description": "Turg'unlik davridagi poraxo'rlik, ma'naviy inqiroz va jamiyatdagi soxtaliklarni dadillik bilan fosh etgan o'tkir roman.",
    "questionCount": 10
  },
  {
    "id": "sariq-devni-minib",
    "title": "Sariq devni minib",
    "author": "Xudoyberdi To'xtaboyev",
    "year": 1968,
    "pages": 280,
    "genre": "Sarguzasht Qissa",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #059669, #047857)",
    "coverTitleColor": "#ECFDF5",
    "coverImage": "",
    "description": "Sehrli qalpoqcha yordamida har xil sarguzashtlarga duch kelgan, dangasalikdan qutilib ilm yo'lini tanlagan Hoshimjon haqida tarbiyaviy hikoya.",
    "questionCount": 10
  },
  {
    "id": "lolazor",
    "title": "Lolazor",
    "author": "Murod Muhammad Do'st",
    "year": 1988,
    "pages": 360,
    "genre": "Falsafiy Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #991B1B, #450A0A)",
    "coverTitleColor": "#FEE2E2",
    "coverImage": "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=600&auto=format&fit=crop&q=80",
    "description": "O'zbek nasrining cho'qqisi: sovet turg'unligi, amaldorlik o'yinlari, Yaxshiboyev va Nazar Yaxshiboyevlar o'rtasidagi ma'naviy duel.",
    "questionCount": 10
  },
  {
    "id": "kafansiz-komilganlar",
    "title": "Kafansiz ko'milganlar",
    "author": "Shukrullo",
    "year": 1989,
    "pages": 240,
    "genre": "Xotira-Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1C1917, #0C0A09)",
    "coverTitleColor": "#F5F5F4",
    "coverImage": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80",
    "description": "Stalin qatag'oni, Sibir surgunining sovuq dahshatlari va nohaq jazolangan begunoh insonlarning matonati haqidagi hujjatli roman.",
    "questionCount": 10
  },
  {
    "id": "temur-tuzuklari",
    "title": "Temur tuzuklari",
    "author": "Amir Temur",
    "year": 1400,
    "pages": 210,
    "genre": "Tarixiy-Huquqiy",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #111827, #0F172A)",
    "coverTitleColor": "#FFFFFF",
    "coverImage": "",
    "description": "Sohibqiron Amir Temurning davlat boshqaruvi, harbiy qonunlar, el-yurt tuzish va saltanat qoidalari bo'yicha tuzgan vasiyat-tuzuklari.",
    "questionCount": 10
  },
  {
    "id": "boburnoma",
    "title": "Boburnoma",
    "author": "Zahiriddin Muhammad Bobur",
    "year": 1530,
    "pages": 480,
    "genre": "Avtobiografik",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1F2937, #374151)",
    "coverTitleColor": "#F9FAFB",
    "coverImage": "",
    "description": "Bobur tomonidan yozilgan tarixiy, geografik va adabiy qomusiy asar. Unda Movarounnahr, Kobul va Hindiston voqealari tasvirlanadi.",
    "questionCount": 10
  },
  {
    "id": "qutadgu-bilig",
    "title": "Qutadg'u bilig (Saodatga eltuvchi bilim)",
    "author": "Yusuf Xos Hojib",
    "year": 1069,
    "pages": 420,
    "genre": "Falsafiy Doston",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #78350F, #92400E)",
    "coverTitleColor": "#FEF3C7",
    "coverImage": "",
    "description": "Kuntug'di, Oytoldi va boshqa timsollar orqali adolatli davlat boshqaruvi va baxtli hayot qonunlari ko'rsatilgan doston.",
    "questionCount": 10
  },
  {
    "id": "hamsa",
    "title": "Xamsa",
    "author": "Alisher Navoiy",
    "year": 1485,
    "pages": 920,
    "genre": "Mumtoz Dostonlar",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E1B4B, #0F172A)",
    "coverTitleColor": "#EDE9FE",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    "description": "Turkiy tildagi birinchi beshlik: 'Hayrat ul-abror', 'Farhod va Shirin', 'Layli va Majnun', 'Sab'ai sayyor', 'Saddi Iskandariy'. Insoniyat tafakkurining yuksak cho'qqisi.",
    "questionCount": 10
  },
  {
    "id": "lison-ut-tayr",
    "title": "Lison ut-tayr (Qush tili)",
    "author": "Alisher Navoiy",
    "year": 1499,
    "pages": 280,
    "genre": "Falsafiy-Irfoniy",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #065F46, #022C22)",
    "coverTitleColor": "#ECFDF5",
    "coverImage": "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=600&auto=format&fit=crop&q=80",
    "description": "Simurg'ni qidirib yo'lga chiqqan qushlarning 7 vodiyni bosib o'tishi orqali insonning o'zligini anglashi va Haqqa yetish falsafasi.",
    "questionCount": 10
  },
  {
    "id": "siyosatnoma",
    "title": "Siyosatnoma",
    "author": "Nizomulmulk",
    "year": 1091,
    "pages": 260,
    "genre": "Siyosiy-Falsafiy",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #854D0E, #A16207)",
    "coverTitleColor": "#FEF9C3",
    "coverImage": "",
    "description": "Saljuqiylar vaziri Nizamulmulkning davlat boshqaruvi, soliqlar, adolat va adolatli amaldorlar haqidagi o'giti.",
    "questionCount": 10
  },
  {
    "id": "qobusnoma",
    "title": "Qobusnoma",
    "author": "Kaykovus",
    "year": 1082,
    "pages": 220,
    "genre": "Pandnoma",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #065F46, #064E3B)",
    "coverTitleColor": "#ECFDF5",
    "coverImage": "",
    "description": "Otadan o'g'liga nasihat tarzida yozilgan, insoniy fazilatlar, hunar o'rganish, oila va do'stlik odoblari to'plami.",
    "questionCount": 10
  },
  {
    "id": "guliston",
    "title": "Guliston",
    "author": "Sa'diy Sheroziy",
    "year": 1258,
    "pages": 240,
    "genre": "Hikmatlar to'plami",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #831843, #500724)",
    "coverTitleColor": "#FDF2F8",
    "coverImage": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
    "description": "Podshohlar odobi, qanoat fazilati, jim turish san'ati va insoniy hikmatlar gavhari bo'lgan o'lmas asar.",
    "questionCount": 10
  },
  {
    "id": "alpomish",
    "title": "Alpomish",
    "author": "Xalq dostoni",
    "year": 1000,
    "pages": 350,
    "genre": "Qahramonlik Dostoni",
    "difficulty": "intermediate",
    "cover": "covers/alpomish.webp",
    "coverBg": "linear-gradient(135deg, #1E3A8A, #1E40AF)",
    "coverTitleColor": "#EFF6FF",
    "coverImage": "covers/alpomish.webp",
    "description": "O'zbek xalq og'zaki ijodining buyuk qahramonlik dostoni. Unda vatanparvarlik, sadoqat va do'stlik tuyg'ulari ulug'lanadi.",
    "questionCount": 10
  },
  {
    "id": "chol-va-dengiz",
    "title": "Chol va dengiz",
    "author": "Ernest Xeminguey",
    "year": 1952,
    "pages": 140,
    "genre": "Falsafiy Qissa",
    "difficulty": "beginner",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #0369A1, #082F49)",
    "coverTitleColor": "#E0F2FE",
    "coverImage": "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
    "description": "Santyagoning ulkan baliq bilan tengsiz kurashi: 'Insonni yengib bo'lmaydi, uni faqat mahv etish mumkin, xolos'.",
    "questionCount": 10
  },
  {
    "id": "martin-iden",
    "title": "Martin Iden",
    "author": "Jek London",
    "year": 1909,
    "pages": 460,
    "genre": "Roman",
    "difficulty": "advanced",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #374151, #1F2937)",
    "coverTitleColor": "#F9FAFB",
    "coverImage": "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=600&auto=format&fit=crop&q=80",
    "description": "Oddiy dengizchining yuksak iroda va mehnat bilan buyuk yozuvchiga aylanishi, soxta burjua jamiyatining fojiasi va ruhiy yolg'izlik.",
    "questionCount": 10
  },
  {
    "id": "graf-monte-kristo",
    "title": "Graf Monte-Kristo",
    "author": "Aleksandr Dyuma",
    "year": 1844,
    "pages": 980,
    "genre": "Sarguzasht / Drama",
    "difficulty": "intermediate",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E1B4B, #0F172A)",
    "coverTitleColor": "#EDE9FE",
    "coverImage": "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&auto=format&fit=crop&q=80",
    "description": "Edmon Dantesning If qal'asidagi 14 yillik tutqunligi, xazina topishi va xiyonatkorlardan o'ch olishi hamda afv etish sabog'i.",
    "questionCount": 10
  },
  {
    "id": "urush-va-tinchlik",
    "title": "Urush va tinchlik",
    "author": "Lev Tolstoy",
    "year": 1869,
    "pages": 250,
    "genre": "Epik Roman",
    "difficulty": "Qiyin",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E293B, #0F172A)",
    "coverTitleColor": "#F8FAFC",
    "coverImage": "",
    "description": "Napoleon urushlari davridagi rus jamiyati, bir nechta aslzoda oilalar hayoti va insoniyat taqdiri haqidagi epik asar.",
    "questionCount": 10
  },
  {
    "id": "qissasi-rabguziy",
    "title": "Qissasi Rabg'uziy",
    "author": "Rabg'uziy",
    "year": 1310,
    "pages": 250,
    "genre": "Diniy-Tarixiy",
    "difficulty": "Qiyin",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #78350F, #5C2D0F)",
    "coverTitleColor": "#FFFBEB",
    "coverImage": "",
    "description": "Payg'ambarlar hayoti va sarguzashtlari haqidagi hikoyalarni o'z ichiga olgan ilk turkiy nasriy asar.",
    "questionCount": 10
  },
  {
    "id": "anna-karenina",
    "title": "Anna Karenina",
    "author": "Lev Tolstoy",
    "year": 1877,
    "pages": 250,
    "genre": "Roman",
    "difficulty": "Qiyin",
    "cover": "covers/anna-karenina.webp",
    "coverBg": "linear-gradient(135deg, #881337, #9F1239)",
    "coverTitleColor": "#FFE4E6",
    "coverImage": "covers/anna-karenina.webp",
    "description": "Anna Kareninaning taqiqlangan sevgisi, oilaviy ziddiyatlar va jamiyat qoliplari fonidagi shaxsiy inqirozi.",
    "questionCount": 10
  },
  {
    "id": "romeo-juliet",
    "title": "Romeo va Juliet",
    "author": "Uilyam Shekspir",
    "year": 1597,
    "pages": 250,
    "genre": "Tragediya",
    "difficulty": "O'rta",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #991B1B, #BE123C)",
    "coverTitleColor": "#FFF1F2",
    "coverImage": "",
    "description": "Ikki dushman oila yoshlarining o'lmas muhabbati va oilalar o'rtasidagi adovat fojiasi haqidagi asar.",
    "questionCount": 10
  },
  {
    "id": "sahih-buxoriy",
    "title": "Al-Jome as-Sahih",
    "author": "Imom Buxoriy",
    "year": 846,
    "pages": 250,
    "genre": "Hadislar to'plami",
    "difficulty": "O'rta",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E3A8A, #14B8A6)",
    "coverTitleColor": "#F0FDFA",
    "coverImage": "",
    "description": "Islom olamidagi eng sahih va ishonchli hadislar to'plami bo'lib, Qur'ondan keyingi eng muhim manba hisoblanadi.",
    "questionCount": 10
  },
  {
    "id": "baxt-kochasi",
    "title": "Baxt ko'chasi",
    "author": "Tohir Malik",
    "year": 1978,
    "pages": 250,
    "genre": "Qissa",
    "difficulty": "Oson",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #115E59, #0D9488)",
    "coverTitleColor": "#CCFBF1",
    "coverImage": "",
    "description": "Yoshlarning hayotda to'g'ri yo'l topishi va ma'naviy tarbiya prinsiplari haqida o'git beruvchi asar.",
    "questionCount": 10
  },
  {
    "id": "muvaffaqiyat-7",
    "title": "Muvaffaqiyatli insonlarning 7 ko'nikmasi",
    "author": "Stiven Kovi",
    "year": 1989,
    "pages": 250,
    "genre": "Shaxsiy Rivojlanish",
    "difficulty": "Qiyin",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #8B5CF6, #6D28D9)",
    "coverTitleColor": "#F5F3FF",
    "coverImage": "",
    "description": "Samaradorlik va insoniylik asoslari, shaxsiy tamoyillar, liderlik qobiliyati va xarakterni rivojlantirish prinsiplari.",
    "questionCount": 10
  },
  {
    "id": "boy-ota-kambagal-ota",
    "title": "Boy ota, kambag'al ota",
    "author": "Robert Kiyosaki",
    "year": 1997,
    "pages": 250,
    "genre": "Moliya / Biznes",
    "difficulty": "Oson",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #10B981, #059669)",
    "coverTitleColor": "#ECFDF5",
    "coverImage": "",
    "description": "Moliyaviy mustaqillikka erishish sirlari, pulni boshqarish, aktiv va passiv tushunchalarini o'rgatuvchi biznes bestseller.",
    "questionCount": 10
  },
  {
    "id": "lissabondagi-tun",
    "title": "Lissabondagi tun",
    "author": "Erix Mariya Remark",
    "year": 1961,
    "pages": 250,
    "genre": "Roman",
    "difficulty": "O'rta",
    "cover": "covers/lissabondagi-tun.jpg",
    "coverBg": "linear-gradient(135deg, #0EA5E9, #2563EB)",
    "coverTitleColor": "#F8FAFC",
    "coverImage": "covers/lissabondagi-tun.jpg",
    "description": "\"Lissabondagi tun\" — 1942-yilda fashizm taʼqibidan qochgan muhojirlarning fojiali qismati va har qanday zulmdan ustun keluvchi buyuk muhabbati haqidagi dramatik roman. Asar chipta evaziga tonggacha aytilgan bir kechalik dardli hayot hikoyasi ustiga qurilgan.",
    "questionCount": 10
  },
  {
    "id": "robinzon-kruzo",
    "title": "Robinzon Kruzo",
    "author": "Daniel Defoe",
    "year": 1719,
    "pages": 250,
    "genre": "Sarguzasht",
    "difficulty": "Oson",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #15803D, #16A34A)",
    "coverTitleColor": "#F0FDF4",
    "coverImage": "",
    "description": "Robinzon Kruzoning kimsasiz orolda 28 yil davomida yolg'iz hayot kechirishi, sabr-toqati va matonati.",
    "questionCount": 10
  },
  {
    "id": "diqqat-deep-work",
    "title": "Diqqat (Deep Work)",
    "author": "Kal Nyuport",
    "year": 2016,
    "pages": 250,
    "genre": "Samaradorlik",
    "difficulty": "O'rta",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #EC4899, #BE123C)",
    "coverTitleColor": "#FFF1F2",
    "coverImage": "",
    "description": "Zamonaviy axborotlar to'lqinida diqqatni jamlash, chalg'imaslik va chuqur ishlash qobiliyatini rivojlantirish.",
    "questionCount": 10
  },
  {
    "id": "faust",
    "title": "Faust",
    "author": "Iogann Volfgang Gyote",
    "year": 1832,
    "pages": 250,
    "genre": "Falsafiy Tragediya",
    "difficulty": "Qiyin",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #581C87, #9D174D)",
    "coverTitleColor": "#FFF1F2",
    "coverImage": "",
    "description": "Doktor Faust va iblis Mefistofel o'rtasidagi inson ruhi, cheksiz bilim va ehtiros to'qnashuvi haqidagi asar.",
    "questionCount": 10
  },
  {
    "id": "samaradorlik-21",
    "title": "Samaradorlikning 21 yo'li",
    "author": "Brayan Treysi",
    "year": 2001,
    "pages": 250,
    "genre": "Samaradorlik",
    "difficulty": "Oson",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #6366F1, #4338CA)",
    "coverTitleColor": "#EEF2F6",
    "coverImage": "",
    "description": "Dangasalikni yengish va eng muhim topshiriqlarni birinchi navbatda bajarish (qurbaqani yeyish) orqali yutuqlarga erishish.",
    "questionCount": 10
  },
  {
    "id": "sherlock-holmes",
    "title": "Sherlock Holmes sarguzashtlari",
    "author": "Artur Konan Doyl",
    "year": 1892,
    "pages": 250,
    "genre": "Detektiv",
    "difficulty": "Oson",
    "cover": "",
    "coverBg": "linear-gradient(135deg, #1E293B, #0F172A)",
    "coverTitleColor": "#F8FAFC",
    "coverImage": "",
    "description": "Daho detektiv Sherlock Holmes va uning hamrohi Doktor Watsonning murakkab va sirli jinoyatlarni fosh etishi.",
    "questionCount": 10
  }
];
