const Q = (q, o, c, e) => ({q, o, c, e});
const BQ = {
  hamsa: [
    Q('"Hamsa" so\'zi nimani anglatadi?', ['Uch','Besh','Yetti','To\'qqiz'],1,'"Hamsa" arabchada "besh" ma\'nosini bildiradi, Navoiyning 5 dostonidan iborat.'),
    Q('Navoiyning "Hamsa"siga kirmagan doston qaysi?', ['Hayrat ul-abror','Farhod va Shirin','Layli va Majnun','Lison ut-tayr'],3,'"Lison ut-tayr" alohida asar, "Hamsa" tarkibiga kirmaydi.'),
    Q('"Farhod va Shirin" dostonining bosh qahramoni kim?', ['Iskandar','Farhod','Majnum','Shirin'],1,'Farhod - mehnatkash, ishqiy va vafodor qahramon, Shirinni sevadi.'),
    Q('"Layli va Majnun" dostonida Majnunning asl ismi nima?', ['Farhod','Qays ibn al-Mulavvah','Ibn Salom','Salam'],1,'Qays ibn al-Mulavvah - Layliga muhabbati tufayli "Majnun" (devona) nomini olgan.'),
    Q('"Sab\'ai sayyor" dostoni mavzusi nima?', ['Bog\'bon','Shoh Bahrom va 7 go\'zal haqida','Dehqon','Baliqchi'],1,'Shoh Bahromning 7 iqlimdagi 7 go\'zal bilan bog\'liq 7 hikoyasi.'),
    Q('"Saddi Iskandariy" dostoni qahramoni?', ['Iskandar Zulqarnayn','Farhod','Majnum','Shirin'],0,'Iskandar Zulqarnayn obrazi orqali komil inson timsoli yaratilgan.'),
    Q('Navoiy "Hamsa"ni qaysi tilda yozgan?', ['Fors','Arab','Turkiy (Chig\'atoy)','Mo\'g\'ul'],2,'O\'zbek tilining chig\'atoy lahjasida, turkiy xalqlar tushunishi uchun.'),
    Q('"Hayrat ul-abror" nimadan iborat?', ['Roman','She\'rlar','20 maqolat (hikmatli so\'z)','Hikoyalar'],2,'20 maqolatdan iborat falsafiy-didaktik doston.'),
    Q('Navoiy "Hamsa"ni kimga taqlid qilib yozgan?', ['Firdavsiy','Jomiy','Nizomiy Ganjaviy','Sa\'diy'],2,'Fors shoiri Nizomiy Ganjaviy (XII asr) "Panj ganj" (Besh xazina)siga taqlid.'),
    Q('Asar necha baytdan iborat?', ['15 000','25 000','35 000','50 000'],3,'Taxminan 50 000 bayt, turkiy adabiyotning ulkan yodgorligi.'),
  ],
  'lison-ut-tayr': [
    Q('"Lison ut-tayr" ma\'nosi?', ['Qushlar tili','Go\'zal bog\'','Uchar kitob','Sehrli dunyo'],0,'"Qushlar tili" - qushlar tilidan yozilgan falsafiy-tasavvufiy doston.'),
    Q('Asosiy syujet?', ['Odamlar sayohati','Qushlarning Simurg\'ni izlashi','Hayvonlar jangi','Sevgi hikoyasi'],1,'Qushlar podshoh Simurg\'ni izlab, 7 vodiydan o\'tadilar.'),
    Q('Nechta vodiy?', ['5','6','7','9'],2,'7 vodiy: Talab, Ishq, Ma\'rifat, Istig\'no, Tavhid, Hayrat, Faqr va Fano.'),
    Q('Qushlar Simurg\'ni qayerda topadilar?', ['Dengizda','Osmonda','O\'zlarida (30 ta qush)','Yer ostida'],2,'Simurg\'ni o\'zlarida topadilar - "Si mur g\'" (forscha 30 ta qush) so\'z o\'yini.'),
    Q('Navoiy bu asarni kimning asari asosida yozgan?', ['Rumiy','Attor','Jomiy','Nizomiy'],1,'Farididdin Attorning "Mantiq ut-tayr" asari asosida (Attor 40 vodiysini 7 ga qisqartirgan).'),
    Q('Asosiy falsafiy g\'oya?', ['Sevgi','Inson o\'zida Haqiqatni topishi mumkin','Boylik','Do\'stlik'],1,'Haqiqatni tashqaridan emas, o\'z ichingdan izlash kerak.'),
    Q('G\'unaysh (dudak) nomli qush nega Simurg\'ga bora olmaydi?', ['Qo\'rqadi','Yo\'l bilmaydi','Haddan oshgan muhabbati to\'sig\'i','Kasal'],2,'Haddan oshgan muhabbati tufayli Simurg\'ga yetisha olmaydi.'),
    Q('Navoiy asarni qachon yozgan?', ['1485','1499','1501','1510'],1,'1499 yil.'),
    Q('Asar uzunligi?', ['1000','2000','3000','4000'],3,'Taxminan 3500 bayt.'),
    Q('Navoiy bu asarni kimga bag\'ishlagan?', ['Sulton Husayn Boyqaro','Jomiy','Nizomiy','Bobur'],0,'Sulton Husayn Boyqaroga bag\'ishlagan.'),
  ],
  boburnoma: [
    Q('"Boburnoma" muallifi?', ['Alisher Navoiy','Zahiriddin Muhammad Bobur','Mirzo Ulug\'bek','Pirimqul Qodirov'],1,'Boburning o\'zi tomonidan yozilgan memuar.'),
    Q('Asar qaysi tilda yozilgan?', ['Fors','Turkiy (Chig\'atoy)','Arab','Hind'],1,'Turkiy tilning chig\'atoy lahjasida, Boburning ona tilida.'),
    Q('Bobur "Boburnoma"da qaysi davrni tasvirlaydi?', ['Faqat Hindiston','1494 dan 1529 gacha','Faqat Bolalik','Faqat harbiy yurishlar'],1,'1494 (otasining o\'limi) dan 1529 gacha bo\'lgan voqealar.'),
    Q('"Boburnoma" qanday janr?', ['Tarixiy roman','Memuar (avtobiografik asar)','She\'riy to\'plam','Ilmiy risola'],1,'Tarixiy-geografik va avtobiografik memuar.'),
    Q('Bobur asarda qaysi jangni batafsil tasvirlaydi?', ['Panipat jangi','Borodino jangi','Sohra jangi','Karbalo jangi'],0,'Panipat jangi (1526) - Hindistondagi birinchi yirik jang.'),
    Q('Asarda Hindistonning qanday xususiyatlari qayd etilgan?', ['Dini','Tabiati, iqlimi, hayvonot dunyosi','Siyosati','Tarixi'],1,'Bobur hind tabiati, iqlimi, o\'simlik va hayvonot dunyosini kuzatgan.'),
    Q('Boburning Farg\'onadagi yillari qanday tasvirlangan?', ['Tinch','Doimiy kurash va taxt talashlar','Boylik','Shon-sharaf'],1,'Doimiy kurash va taxt talashlari, qiyin davr.'),
    Q('"Boburnoma" necha bobdan iborat?', ['1 bob','3 bob','10 bob','4 bob'],3,'10 bob (ba\'zi nusxalarda farqlanadi).'),
    Q('Asarning jahon adabiyotidagi o\'rni?', ['Oddiy kundalik','Nodir avtobiografik asar, qimmatli tarixiy manba','Fantastika','Diniy'],1,'Nodir avtobiografik asar, Markaziy va Janubiy Osiyo tarixi uchun muhim manba.'),
    Q('Bobur qachon vafot etgan?', ['1526','1530','1535','1540'],1,'1530 yil 26 dekabr, Agra shahrida.'),
  ],
  'qutadgu-bilig': [
    Q('Muallifi?', ['Mahmud Qashg\'ariy','Yusuf Xos Hojib','Ahmad Yassaviy','Rabg\'uziy'],1,'Yusuf Xos Hojib (Yusuf Balasoguni).'),
    Q('"Qutadg\'u bilig" ma\'nosi?', ['Quvvatli bilim','Saodatli bilim yoki baxt keltiruvchi bilim','Qadimgi bilim','Ko\'p bilim'],1,'"Saodatli bilim" yoki "Baxt keltiruvchi bilim".'),
    Q('Asarda nechta ramziy qahramon?', ['2','3','4','5'],2,'4 ta: Kuntug\'di (adolat), Oytoldi (baxt), O\'gdulmish (aql), O\'gdur mish (qanoat).'),
    Q('Qahramonlar qanday ramz?', ['Hayvonlar','Insoniy fazilatlar va tushunchalar','O\'simliklar','Samoviy jismlar'],1,'Adolat, davlat, aql va qanoat kabi tushunchalar ramziy ifodasi.'),
    Q('Asar necha bayt?', ['3 000','6 000','6 645','10 000'],2,'6 645 bayt (13 000 misra).'),
    Q('Qaysi tilda yozilgan?', ['Arab','Fors','Turkiy','Mo\'g\'ul'],2,'Turkiy tilda - islomiy turkiy adabiyotning ilk yodgorligi.'),
    Q('Qaysi shaharda yozilgan?', ['Samarqand','Qashg\'ar','Buxoro','Bag\'dod'],1,'Qashg\'ar shahrida.'),
    Q('Kimga taqdim etilgan?', ['Sulton Mahmud Qashg\'ariy','Tabg\'ach Bug\'raxon','Alp Arslon','Malikshoh'],1,'Qashg\'ar hukmdori Tabg\'ach Bug\'raxonga.'),
    Q('Asosiy mavzusi?', ['Sevgi va sadoqat','Adolatli davlat boshqaruvi va baxtli hayot','Harbiy yurishlar','Tibbiyot'],1,'Adolatli boshqaruv, baxtli hayot va komil inson tarbiyasi.'),
    Q('Qachon yozilgan?', ['1069','1070','1074','1080'],0,'1069-1070 yillarda.'),
  ],
  'devonu-lugotit-turk': [
    Q('Muallifi?', ['Yusuf Xos Hojib','Mahmud Qashg\'ariy','Alisher Navoiy','Kaykovus'],1,'Mahmud ibn Husayn ibn Muhammad Qashg\'ariy.'),
    Q('Asar mazmuni?', ['Faqat she\'r','Turkiy xalqlarning ilk qomusi, lug\'at va ensiklopediya','Faqat grammatika','Diniy asar'],1,'Turkiy qabilalar tili, adabiyoti, geografiyasi va madaniyati haqida.'),
    Q('Asarda nechta turkiy qabila tiliga oid so\'z bor?', ['5 000','7 500','9 000','10 000'],2,'9 000 dan ortiq so\'z va iboralar.'),
    Q('Qaysi tilda yozilgan?', ['Turkcha','Arab','Fors','Mo\'g\'ul'],1,'Arab tilida, arablarga turkiy tillarni o\'rgatish maqsadida.'),
    Q('Asarda birinchi marta nima tasvirlangan?', ['Xarita','Turkiy xalqlar xaritasi','Samoviy jismlar','Hayvonlar'],1,'Dunyodagi birinchi turkiy xalqlar xaritasi.'),
    Q('Qachon yozilgan?', ['1069','1070','1072-1074','1080'],2,'1072-1074 yillarda, Bag\'dodda.'),
    Q('Kimga bag\'ishlangan?', ['Sulton Malikshoh','Abbosiy xalifa Muqtadir billoh','Tabg\'ach Bug\'raxon','Alp Arslon'],1,'Abbosiy xalifa Muqtadir billohga.'),
    Q('Asarning yana bir nomi?', ['Turkiy so\'zlar devoni','Qomus','Lug\'at','Majmua'],0,'"Turkiy so\'zlar devoni" deb ham ataladi.'),
    Q('Mahmud Qashg\'ariy qayerdan edi?', ['Samarqand','Buxoro','Qashg\'ar','Bag\'dod'],2,'Qashg\'ardan, turkiy qabilalardan biri.'),
    Q('Asar necha bob?', ['4 bob','7 bob','8 bob','10 bob'],2,'8 bob, ot, fe\'l va boshqa qismlarga bo\'linadi.'),
  ],
  alpomish: [
    Q('Alpomish qahramoni kim?', ['Toxir ibn Asad','Hakimbek (Alpomish)','Yusuf','Tohir'],1,'Hakimbek - Alpomish nomi bilan mashhur qahramon.'),
    Q('Alpomishning sevgilisi kim?', ['Qorajon','Barchin','Oysa','Kumush'],1,'Barchin - Alpomishning sevgilisi va rafiqasi.'),
    Q('Alpomish qayerda asirlikda bo\'ladi?', ['Misr','Qorajon (Kalmak) yurtida','Hindiston','Rum'],1,'Qorajon yurtida 7 yil asirlikda.'),
    Q('Doston qanday mavzuda?', ['Sevgi fojiasi','Vatanparvarlik, jasorat va sadoqat','Boylik','Ilm'],1,'Vatanparvarlik, jasorat, do\'stlik va sevgiga sadoqat.'),
    Q('Alpomishning quroli?', ['Qilich','Kamon va nayza','To\'qmoq','Tayoq'],0,'Qilich va kamon, ayniqsa mashhur nayzasi.'),
    Q('Alpomish qaysi elat vakili?', ['Qo\'ng\'irot','Qarluq','O\'g\'uz','Qipchoq'],0,'Qo\'ng\'irot elatining baxshi va qo\'shiqchilari orqali yetib kelgan.'),
    Q('Barchinning Alpomishga sadoqati qanday namoyon?', ['Urushadi','7 yil kutadi va o\'z joniga qasd qilmaydi','Qochadi','Sovchi yuboradi'],1,'Alpomish 7 yil asirlikda, Barchin unga sodiq qoladi.'),
    Q('Doston taxminan qachon yaratilgan?', ['500','1000','1200','1500'],1,'Taxminan 1000 yil atrofida, xalq og\'zaki ijodi.'),
    Q('Alpomishni asirlikdan kim qutqaradi?', ['Barchin','Otasi','Do\'sti Qorajon','O\'zi qochadi'],3,'Qorajonning qizi orqali qochishga muvaffaq bo\'ladi.'),
    Q('Doston o\'zbek xalqining qanday fazilatini ulug\'laydi?', ['Boylik','Jasorat, vafo va vatanparvarlik','Ayyorlik','Kuch'],1,'Jasorat, vafo, vatanparvarlik va do\'stlik.'),
  ],
  gorogli: [
    Q('Go\'ro\'g\'li turkumi qanday doston?', ['Bir doston','Dostonlar turkumi','Roman','She\'r'],1,'Turkum dostonlar - Go\'ro\'g\'li va uning qahramonlari haqida.'),
    Q('Go\'ro\'g\'lining yurti?', ['Buxoro','Samarqand','Chambil','Xiva'],2,'Chambil yurti - afsonaviy makon.'),
    Q('Go\'ro\'g\'lining oti?', ['Rosinant','G\'irot','Boychibor','Duldul'],1,'G\'irot - Go\'ro\'g\'lining afsonaviy oti.'),
    Q('Go\'ro\'g\'lining asosiy maqsadi?', ['Boylik','Adolat va ozodlik','Shon-sharaf','Sevgi'],1,'Adolat va ozodlik uchun kurash.'),
    Q('Go\'ro\'g\'lining eng mashhur do\'sti?', ['Maston','Alpomish','Yusuf','Tohir'],0,'Maston - yaqin do\'sti va safdoshi.'),
    Q('Dostonlarda qanday voqealar tasvirlangan?', ['Tinch hayot','Harbiy yurishlar va sarguzashtlar','Siyosat','Savdo'],1,'Harbiy yurishlar, sarguzasht va jasoratli voqealar.'),
    Q('Go\'ro\'g\'li obrzining o\'zbek xalqidagi o\'rni?', ['Kamsitilgan','Xalq qahramoni va adolat himoyachisi','Yovuz qahramon','Oddiy odam'],1,'Xalq qahramoni, adolat himoyachisi va ideal hukmdor timsoli.'),
    Q('Doston turkumi qachon yaratilgan?', ['500','1000','1500','1700'],1,'Taxminan 1000 yil atrofida paydo bo\'lgan.'),
    Q('Go\'ro\'g\'lining dushmanlari?', ['Do\'stlar','Adolatsiz hukmdorlar va bosqinchilar','Odamlar','Hayvonlar'],1,'Adolatsiz hukmdorlar va zolim bosqinchilar.'),
    Q('Go\'ro\'g\'lining Chambil yurti qanday makon?', ['Haqiqiy','Afsonaviy ideal davlat','Tarixiy','Yo\'qolgan'],1,'Afsonaviy, erkin va adolatli ideal davlat makoni.'),
  ],
  'qissasi-rabguziy': [
    Q('Muallifi?', ['Mahmud Qashg\'ariy','Rabg\'uziy (Nosiruddin)','Yusuf Xos Hojib','Kaykovus'],1,'Rabg\'uziy (Nosiruddin Burhonuddin Rabg\'uziy).'),
    Q('Asar mazmuni?', ['Sevgi hikoyasi','Payg\'ambarlar hayoti haqidagi hikoyalar','Ilmiy asar','Lug\'at'],1,'Payg\'ambarlar hayoti va sarguzashtlari haqidagi hikoyalar.'),
    Q("Asar turkiy adabiyotda qanday o'rin tutadi?", ['Ilmiy asar','Ilk turkiy nasriy asarlardan biri','Yagona asar','Zamonaviy'],1,'Ilk turkiy nasriy asarlardan biri.'),
    Q('Qachon yozilgan?', ['1300','1310','1320','1350'],1,'1310 yil.'),
    Q('Asar qaysi tilda?', ['Fors','Arab','Turkiy','Mo\'g\'ul'],2,'Turkiy tilda.'),
    Q('"Rabg\'uziy" taxallusi qayerdan olingan?', ['Tug\'ilgan shahardan','Rabg\'uz - tug\'ilgan joy nomidan','Otasidan','Maktabdan'],1,'Rabg\'uz shahridan (hozirgi Qozog\'iston).'),
    Q("Asar necha qismdan iborat?", ['30','50','72','100'],2,'72 (ba\'zi manbalarda 75) qissa.'),
    Q('Kim uchun yozilgan?', ['Sulton','Oddiy xalq tushunishi uchun','Olimlar','Arab sayohatchilar'],1,'Oddiy turkiy xalq tushunishi uchun.'),
    Q('Qissalar asosan qanday mavzuda?', ['Sevgi','Payg\'ambarlar mo\'jizalari va ibratli hayoti','Sarguzasht','Harbiy'],1,'Payg\'ambarlar hayoti va ibratli voqealar.'),
    Q('Asarning yana bir nomi?', ['Hamsa','Qissai Rabg\'uziy yoki Rabg\'uziy qissalari','Boburnoma','Guliston'],1,'"Qissai Rabg\'uziy" yoki "Qisasi Rabg\'uziy".'),
  ],
  'sahih-buxoriy': [
    Q('Muallifi?', ['Imom Muslim','Imom Buxoriy','Imom Termiziy','Imom Nasoiy'],1,'Muhammad ibn Ismoil al-Buxoriy (Imom Buxoriy).'),
    Q('"Al-Jome as-Sahih" mazmuni?', ['Falosafiy asar','Eng ishonchli hadislar to\'plami','Tarixiy asar','Lug\'at'],1,'Eng sahih (ishonchli) hadislar to\'plami.'),
    Q('Nechta hadisni o\'z ichiga oladi?', ['2 000','7 275','10 000','15 000'],1,'7 275 hadis (takrorlarni hisobga olmaganda).'),
    Q('Imom Buxoriy necha yil davomida asarni yozgan?', ['10','16','20','25'],1,'16 yil davomida (846 yilda tugallangan).'),
    Q('Hadislarni tanlash mezoni?', ['Tasodifiy','Qattiq ishonchlilik talabi - 300 000 hadisdan 7 275 ni tanlab olgan','Barcha hadislarni kiritgan','Faqat oshkora'],1,'300 000 hadisdan faqat eng ishonchlilarini qattiq mezon bilan tanlagan.'),
    Q('Imom Buxoriy qayerda tug\'ilgan?', ['Samarqand','Buxoro','Termiz','Nishopur'],1,'Buxoro shahrida (809 yil 20 iyul).'),
    Q('Asarning islom olamidagi o\'rni?', ['Oddiy kitob','Qur\'ondan keyin ikkinchi eng muhim manba','Ilmiy asar','Tarixiy'],1,'Qur\'oni Karimdan keyin eng sahih manba hisoblanadi.'),
    Q('Necha kitob (bob) dan iborat?', ['50','97','100','150'],1,'97 kitob (bob) dan iborat.'),
    Q('Asar nechada tugallangan?', ['840','844','846','850'],2,'846 yil (hijriy 232).'),
    Q('Imom Buxoriy qayerda vafot etgan?', ['Buxoro','Samarqand','Termiz','Nishopur'],0,'Buxoro yaqinidagi Xartang qishlog\'ida (870 yil).'),
  ],
  'ruhiy-tarbiya': [
    Q('Muallifi?', ['Imom Buxoriy','Imom al-Gazzoliy','Imom Termiziy','Imom Gazzoliy'],1,'Imom al-Gazzoliy (Abu Homid Muhammad al-Gazzoliy).'),
    Q('Asar mazmuni?', ['Hadislar','Qalblarni poklash, ruh tarbiyasi va diniy odoblar','Lug\'at','Tarix'],1,'Qalblarni poklash va ruh tarbiyasi, islomiy odoblar.'),
    Q('Asarning to\'liq nomi?', ['Al-Jome as-Sahih','Ihyo ulumid-din (Diniy ilmlarni tiriltirish)','Qutadg\'u bilig','Guliston'],1,'"Ihyo ulumid-din" - Diniy ilmlarni tiriltirish.'),
    Q('Nechta jild?', ['2','3','4','5'],2,'4 jild.'),
    Q('Har bir jild necha bob?', ['5','10','10 (jami 40 bob)','8'],2,'Har bir jild 10 bob, jami 40 bob.'),
    Q('Asar qaysi tilda?', ['Fors','Arab','Turkiy','Mo\'g\'ul'],1,'Arab tilida.'),
    Q('Gazzoliy qaysi asrda yashagan?', ['IX','X','XI-XII','XIII'],2,'1058-1111 yillarda (XI-XII asrlar).'),
    Q('Asosiy mavzu?', ['Tibbiyot','Nafsni poklash, xulq va ruhiy kamolot','Astronomiya','Arxitektura'],1,'Nafsni poklash, to\'g\'ri xulq va ruhiy kamolot.'),
    Q("Gazzoliy qanday sohada mashhur?", ['Tibbiyot','Falsafa va islom ilohiyoti','Astronomiya','Matematika'],1,'Falsafa va islom ilohiyoti, "Islom hujjati" deb ulug\'lanadi.'),
    Q('Asar nechanchi yilda yozilgan?', ['1095','1100','1105','1111'],2,'1105 yil atrofida.'),
  ],
  hamlet: [
    Q('"Hamlet" tragediyasida qirol Klavdiy Hamletga nisbatan kim bo\'ladi?', ['Amakisi','Otasi','Akasi','Buvasi'],0,'Klavdiy Hamletning amakisi bo\'lib, u Hamletning otasini o\'ldirib, taxt va qirolichaga ega chiqadi.'),
    Q('Hamlet "Yoki bo\'lmoq, yoki bo\'lmaslik" monologini qayerda aytadi?', ['Qasr devorida','Qabristonda','Saroy zalida','Onasining xonasida'],1,'Hamlet bu monologni qabristonda, bosh suyagiga qarab hayot va o\'lim haqida mulohaza yuritayotganda aytadi.'),
    Q('Hamlet sevgan qiz Poloniyning qizi kim?', ['Ofeliya','Gertruda','Yorik','Yuliy'],0,'Ofeliya - Poloniyning qizi va Hamletning sevgilisi. U otasining o\'limidan keyin aqldan ozadi.'),
    Q('"Spektakl ichida spektakl" sahnasining maqsadi nima?', ['Shohona tomosha','Klavdiyning aybini fosh etish','Ofeliyani sevish','Aqldan ozganlikni ko\'rsatish'],1,'Hamlet aktyorlar yordamida otasining o\'ldirilishi sahnalashtirilgan spektaklni qo\'yib, Klavdiyning reaksiyasini kuzatadi.'),
    Q('Hamletning eng yaqin do\'sti kim?', ['Rozenkrans','Gildenstern','Horatsiy','Laert'],2,'Horatsiy Hamletning eng sodiq do\'sti bo\'lib, u asar oxirida tirik qoladi.'),
    Q('"Hamlet" asosiy mavzusi nima?', ['Sevgi va sadoqat','Qasos va ikkilanish','Boylik va hokimiyat','Do\'stlik va xiyonat'],1,'Asosiy mavzu - qasos va ikkilanish, Hamlet otasining o\'limi uchun qasos olishda ikkilanadi.'),
    Q('Ofeliyaning o\'limi qanday?', ['Qilich bilan o\'ldiriladi','Zahar ichadi','Daryoga cho\'kib ketadi','Saroy devoridan yiqiladi'],2,'Ofeliya aqldan ozgan holda daryo bo\'yida gulchambarlar to\'qib yurganida suvga tushib cho\'kadi.'),
    Q('Hamlet otasining sharpasini qayerda ko\'radi?', ['Saroyda','Qasr devori ustida','Qabristonda','O\'rmonda'],1,'Qirolning sharpasi birinchi marta qasr devori ustida, tungi soqchilarga ko\'rinadi.'),
    Q('Qirolicha Gertruda kimga turmushga chiqadi?', ['Hamletning otasiga','Klavdiyga','Poloniyga','Laertga'],1,'Gertruda - Hamletning onasi, eri vafot etgach, uning ukasi Klavdiyga turmushga chiqadi.'),
    Q('Asar oxirida nima yuz beradi?', ['Hamlet qirol bo\'ladi','Hamlet va dushmanlari halok bo\'ladi','Hamlet Ofeliyaga uylanadi','Hamlet Angliyaga ketadi'],1,'Asar oxirida zaharli qilich va sharob tufayli Gertruda, Laert, Klavdiy va Hamlet ham halok bo\'ladi.'),
  ],
  'romeo-juliet': [
    Q('Asar voqealari qaysi shaharda?', ['Venetsiya','Verona','Florensiya','Milan'],1,'Verona shahri.'),
    Q('Ruhoniy Romeo va Julietni kim nikohlab qo\'yadi?', ['Lavrentiy','Benedikt','Franchisko','Antonio'],0,'Ruhoniy Lavrentiy ularning yashirin nikohini o\'qib beradi.'),
    Q('Romeo nega Veronadan haydaladi?', ['O\'g\'rilik','Tibaltni o\'ldirgani','Qirolga qarshi chiqqani','Sevgi sirlarini oshkor qilgani'],1,'Romeo Julietning amakivachchasi Tibaltni o\'ldirgani uchun haydaladi.'),
    Q('Juliet qanday hiyla ishlatadi?', ['Erkak kiyimida yashirinadi','O\'limga o\'xshash uyqu dorisi','Shahardan qochadi','Ruhoniyga yashirinadi'],1,'Ruhoniy Lavrentiy Julietga uni 42 soatga o\'likdek uyquga olib ketadigan dori beradi.'),
    Q('Romeo va Juliet qayerda uchrashadilar?', ['Bo\'zorda','Kapulettilar ziyofatida','Cherkovda','Bog\'da'],1,'Maskarad ziyofatida.'),
    Q('Balkon sahnasi qayerda?', ['Saroyda','Kapulettilar bog\'ida','Maydonda','Cherkovda'],1,'Romeo Kapulettilar bog\'iga kiradi va Julietni balkonda sevgi izhor qilayotganini eshitadi.'),
    Q('Merkutsiy kim?', ['Romeoning ukasi','Eng yaqin do\'sti','Dushmani','Otasi'],1,'Romeoning eng yaqin do\'sti, Tibalt bilan jangda halok bo\'ladi.'),
    Q('"Star-crossed lovers" ma\'nosi?', ['Boy edilar','Taqdiri fojiali','Mashhur edi','Uzoq yashadilar'],1,'Taqdiri yulduzlar tomonidan belgilangan, sevgisi fojiali yakunga mahkum.'),
    Q('Asar oxirida oilalar?', ['Urush davom etadi','Yarashadilar','Monteki ketadi','Kapuletti hukmronlik qiladi'],1,'Farzandlarining o\'limidan so\'ng ikki oila adovatni to\'xtatadi.'),
    Q('Romeo o\'z joniga qasd qilgan joy?', ['O\'z uyida','Cherkovda','Kapulettilar qabrida','Maydonda'],2,'Kapulettilar oila qabrida zahar ichib.'),
  ],
  'jinoyat-va-jazo': [
    Q('Bosh qahramon kim?', ['Porfiriy','Razumixin','Rodion Raskolnikov','Svidrigaylov'],2,'Rodion Romanovich Raskolnikov - sobiq huquqshunos talaba.'),
    Q('Raskolnikov kimlarni o\'ldiradi?', ['Savdogarni','Kampir sudxo\'r va singlisini','Amaldorni','Ruhoniyni'],1,'Keksa kampir sudxo\'r Alena Ivanovna va uning singlisi Lizavetani.'),
    Q('Jinoyatini kimga tan oladi?', ['Porfiriyga','Onasiga','Sonya Marmeladovaga','Razumixinga'],2,'Sonyaga, chunki u ham "jinoyat" qilgan - oilasini boqish uchun fohishalik.'),
    Q('Raskolnikovning nazariyasi?', ['Barcha teng','Odamlar oddiy va yuqori toifalarga bo\'linadi','Jinoyat jazolanadi','Pul hamma narsa'],1,'"Yuqori" odamlar qonundan ustun, "oddiy" odamlar esa bo\'ysunadi.'),
    Q('Tergovchi Porfiriy?', ['Darhol qamaydi','Aybdorligini biladi, tan olishini kutadi','O\'zini oqlaydi','Shubhalanmaydi'],1,'Porfiriy Petrovich aqlli tergovchi, psixologik jihatdan tan olishga majbur qiladi.'),
    Q('Asar qaysi shaharda?', ['Moskva','Kiyev','Peterburg','Novgorod'],2,'Peterburg. Dostoevskiy shaharning iflos va ma\'yus ko\'chalarini tasvirlaydi.'),
    Q('Dunya kimga turmushga chiqmoqchi?', ['Svidrigaylovga','Lujinga','Razumixinga','Porfiriyga'],1,'Boy va nomaqbul amaldor Lujinga, akasi Raskolnikovning ta\'limi uchun.'),
    Q('Raskolnikov qanday jazo oladi?', ['O\'lim','Sibirga 8 yil katorga','15 yil qamoq','Ozodlik'],1,'Ixtiyoriy ravishda jinoyatini tan oladi va Sibirga katorgaga hukm qilinadi.'),
    Q('Romanning asosiy g\'oyasi?', ['Jinoyat foydali','Vijdon azobi bilan jazolanadi','Boylik hamma narsa','Huquq muhim emas'],1,'Har qanday jinoyat, "oliy maqsad" uchun bo\'lsa ham, vijdon azobiga mahkum qiladi.'),
    Q('Sonya maslahati?', ['Qochish','Tan olmaslik','Jinoyatni tan olib tavba qilish','O\'z joniga qasd qilish'],2,'Ommaviy tan olish va tavba qilish, u buni qilganda ruhiy tinchlik topadi.'),
  ],
  'urush-va-tinchlik': [
    Q('Qaysi urush davri?', ['Birinchi jahon','Napoleon urushlari','Fuqarolar','Yetti yillik'],1,'Napoleon Bonapartning Rossiyaga bostirib kelishi (1812) va undan oldingi davr.'),
    Q('Per Bezuxov qanday meros oladi?', ['Kichik mulk','Katta boylik va unvon','Qarz','Yer'],1,'Graf Bezuxovning noqonuniy o\'g\'li, otasining o\'limidan keyin katta boylik va graf unvonini oladi.'),
    Q('Natasha Rostova xarakteri?', ['Jim va sokin',"Jonli, hissiyotli va jo'shqin",'Mantiqiy sovuq','Ochko\'z'],1,'Hayotga to\'la, hissiyotli, jonli va ichki go\'zallikka ega, Tolstoyning sevimli qahramoni.'),
    Q('Andrey Bolkonskiy qayerda yaralanadi?', ['Moskvada','Borodino jangida','Peterburgda','Fransiyada'],1,'Borodino jangida og\'ir yaralanadi va vafot etadi.'),
    Q('Asar necha jild?', ['2 jild','4 jild va epilog','3 jild','5 jild'],1,'4 jild va epilog, 500 dan ortiq qahramon.'),
    Q('Perning Napoleonga munosabati?', ['Yomon ko\'rardi','Qoyil edi, keyin hafsalasi pir bo\'ldi','Befarq','Jang qilishni istamadi'],1,'Dastlab qoyil, keyin shafqatsizligini ko\'rib hafsalasi pir bo\'ladi.'),
    Q('Andrey Austerlitsda nima kashf qiladi?', ['G\'alaba','Shon-shuhrat ma\'nosizligini tushunadi','Napoleon bilan uchrashadi','O\'z qo\'shinini topadi'],1,'Osmonga qarab, shon-shuhrat va urushning behudaligini his qiladi.'),
    Q('Napoleonning Moskvaga kirishi?', ['Tantana bilan kutib oladi','Moskva tashlab ketiladi va yonadi','Ruslar taslim bo\'ladi','Napoleon Moskvada qoladi'],1,'Ruslar Moskvani tashlab ketadi, shahar yonib ketadi.'),
    Q('Natasha kimga uylanadi?', ['Andreyga','Anatol Kuraginga','Per Bezuxovga','Nikolay Rostovga'],2,'Sinovlardan so\'ng Per Bezuxovga uylanadi, 4 farzandli bo\'ladi.'),
    Q('Platon Karatayev nimani ifodalaydi?', ['Rus zodagonini','Xalq donishmandligini','Fransuz ofitserini','Dehqon qo\'zg\'olonchisini'],1,'Oddiy rus xalq donishmandligi, soddalik, sabr-toqat va hayotni sevish.'),
  ],
  'anna-karenina': [
    Q('Mashhur birinchi jumla?', ['"Vaqt o\'tadi..."','"Baxtli oilalar bir-biriga o\'xshaydi..."','"Bir paytlar..."','"Rossiya buyuk davlat..."'],1,'"Baxtli oilalar bir-biriga o\'xshaydi, har bir baxtsiz oila o\'zicha baxtsizdir."'),
    Q('Annaning eri?', ['Vronskiy','Karenin','Levin','Stiva'],1,'Aleksey Aleksandrovich Karenin, yuqori martabali davlat amaldori, sovuq va rasmiy.'),
    Q('Anna Vronskiy bilan qayerda tanishadi?', ['Peterburg balida','Moskva vokzalida','O\'z uyida','Teatrda'],1,'Moskva vokzalida, bir odam poyezd ostida qolib o\'ladi.'),
    Q('Anna jamiyatda qanday munosabatga duch keladi?', ['Qo\'llab-quvvatlanadi','Tahqir va chetlashish','Befarq qaraladi','Mukofotlanadi'],1,'Yuqori jamiyat Annani ijtimoiy tadbirlardan chetlashtiradi.'),
    Q('Levin obrazi kimning aksi?', ['Zodagonlarnikini','Tolstoyning o\'z qarashlari','Dehqonlarnikini','Amaldorlarnikini'],1,'Avtobiografik xususiyatga ega, Tolstoyning qishloq hayoti haqidagi qarashlari.'),
    Q('Anna o\'z joniga qanday qasd qiladi?', ['Zahar ichadi','Daryoga tashlanadi','Poyezd ostiga tashlanadi','O\'zini osadi'],2,'Poyezd ostiga o\'zini tashlab.'),
    Q('Anna va Kareninning o\'g\'li?', ['Seryoja','Petya','Ivan','Aleksey'],0,'Seryoja (Sergey). Anna uni juda sevadi, ajrashgandan keyin ko\'rolmaydi.'),
    Q('Kitty kimga turmushga chiqadi?', ['Vronskiyga','Stivaga','Levinga','Kareninga'],2,'Konstantin Levinga baxtli oila qurib, qishloqda hayot kechiradi.'),
    Q('Levin va Kitty munosabati?', ['Fojiali','Baxtli oila','Ajrashishadi','Birga qochishadi'],1,'Anna va Vronskiy fojiasiga qarama-qarshi - baxtli oila namunasi.'),
    Q('Roman janri?', ['Tarixiy','Psixologik roman','Sarguzasht','Detektiv'],1,'Chuqur psixologik roman, qahramonlarning ichki dunyosi tahlil qilinadi.'),
  ],
  'robinzon-kruzo': [
    Q('Asar muallifi kim?', ['Jonatan Svift','Daniel Defoe','Robert Lyuis Stivenson','Jules Vern'],1,'Daniel Defoe, 1719.'),
    Q('Robinzon orolda necha yil?', ['15','20','28','35'],2,'28 yil, 2 oy va 19 kun.'),
    Q('Mahalliy aholi vakiliga qanday ism beradi?', ['Piter','Juma','Tom','Ben'],1,'Juma (Friday) - haftaning shu kunida topgani uchun.'),
    Q('Birinchi nima o\'zlashtiradi?', ['Baliq ovlash','Ovchilik','Bug\'doy yetishtirish','Uy qurish'],2,'Kemadan topgan bug\'doy donalarini ekib hosil yetishtiradi.'),
    Q('Oroldan qanday qutuladi?', ['Kema yasaydi','O\'tib ketayotgan kema oladi','Juma bilan qayiqda suzadi','Vertolyot keladi'],1,'Ingliz kemasi bilan bog\'lanib, qo\'zg\'olonni bostirishga yordam beradi.'),
    Q('Jumaga qanday til o\'rgatadi?', ['Fransuz','Ingliz','Ispan','Portugal'],1,'Ingliz tilini o\'rgatadi.'),
    Q('Qanday hayvonlarni qo\'lga o\'rgatadi?', ['Yo\'lbars','Echkilar','Fillar','Maymunlar'],1,'Yovvoyi echkilarni sut va go\'sht uchun boqadi.'),
    Q('Asosiy g\'oya?', ['Tabiatga qarshi kurash','Inson irodasi va sabr-toqati','Sevgi','Kashfiyotlar'],1,'Insonning og\'ir sharoitlarda omon qolish qobiliyati va mehnatsevarligi.'),
    Q('Robinzon necha yoshida dengizga chiqadi?', ['16','19','22','25'],1,'19 yoshida otasiga qarshi chiqib dengizga otlanadi.'),
    Q('Kemadan birinchi nima oladi?', ['Oltin','Qurol va asboblar','Kitoblar','Kiyimlar'],1,'Qurol, porox va asboblar - omon qolish uchun eng zarur narsalar.'),
  ],
  'don-kixot': [
    Q('Asar muallifi?', ['Lope de Vega','Migel de Servantes','Kalderon','Garsilaso'],1,'Migel de Servantes Saavedra.'),
    Q('Don Kixotning asl ismi?', ['Alonso Kixana','Sancho Panza','Fernando','Luis'],0,'Alonso Kixana - o\'zini ritsar deb atab ismini o\'zgartirgan.'),
    Q('Otining ismi?', ['Rosinant','Buesefalo','Babieka','Pegaso'],0,'Rosinant - "bir paytlar ot bo\'lgan" ma\'nosida.'),
    Q('Sancho Panza minadigan hayvon?', ['Ot','Eshak','Xachir','Tuya'],1,'O\'zining sodiq eshagini minadi.'),
    Q('Shamol tegirmonlariga nima deb jang qiladi?', ['Dushman qal\'asi','Devlar','Sehrli daraxlar','Ajdarho'],1,'Bahaybat devlar deb o\'ylab hujum qiladi.'),
    Q('Xayoliy sevgilisi?', ['Dulseya del Toboso','Rosinant','Kilsona','Mersedes'],0,'Aslida oddiy dehqon qizi Aldonsa, Don Kixot uni go\'zal malika deb tasavvur qiladi.'),
    Q('Qanday kitoblarni yaxshi ko\'radi?', ['Ilmiy','Ritsarlik romanlari','She\'riy','Tarixiy'],1,'Ritsarlik romanlariga berilib, o\'zi ritsar bo\'lib sayohatga chiqadi.'),
    Q('Sancho Panza xarakteri?', ['Bilimdon','Oddiy, amaliy va hazilkash','Boy','Jangovar'],1,'Oddiy dehqon, realizmi Don Kixotning idealizmiga qarama-qarshi.'),
    Q('Ikkinchi qismida kim bilan uchrashadi?', ['Qirol','Samson Karrasko','Sehrgar','Malika'],1,'Bakalavr Samson Karrasko Don Kixotni yengib uyiga qaytaradi.'),
    Q('Asar qaysi tilda?', ['Lotin','Italyan','Ispan','Fransuz'],2,'Ispan tilida - ispan adabiyotining eng buyuk durdonasi.'),
  ],
  faust: [
    Q('Asar muallifi?', ['Shiller','Gote','Geyne','Lessing'],1,'Iogann Volfgang fon Gote.'),
    Q('Iblis nomi?', ['Lyutsifer','Belzebul','Mefistofel','Satan'],2,'Mefistofel - Xudo bilan bahsdan so\'ng Faustni yo\'ldan urishga harakat qiladi.'),
    Q('Faust qanday kasb egasi?', ['Savdogar','Doktor va olim','Harbiy','Rassom'],1,'Ilohiyot, tibbiyot, huquq va falsafani o\'rgangan olim.'),
    Q('Mefistofel bilan shartnoma?', ['Xizmat qiladi, to\'ysa ruhini oladi','Pul beradi','Do\'stlashadi','Qochadi'],0,'Mefistofel xizmat qiladi, Faust bir lahzadan "To\'xta!" desa ruhini beradi.'),
    Q('Margarita taqdiri?', ['Uylanadi','Farzandini o\'ldirgani uchun qatl','Ajraladi','Kasal bo\'lib o\'ladi'],1,'Faustdan homilador bo\'lib, farzandini o\'ldirgani uchun qatl qilinadi.'),
    Q('Asar janri?', ['Komediya','Falsafiy tragediya','Detektiv','Sarguzasht'],1,'Falsafiy tragediya - inson ruhi va bilimga intilish haqida.'),
    Q('"Prolog osmonda" qayerda?', ['Yerda','Do\'zaxda','Osmonda Xudo va Mefistofel suhbati','Faust uyida'],2,'Xudo va Mefistofel inson tabiati haqida bahslashadilar.'),
    Q('Gote necha yil yozgan?', ['10','20','30','60'],3,'60 yil davomida (1772-1832).'),
    Q('Faust ruhi oxiri?', ['Do\'zaxga tushadi','Mefistofelga beriladi','Osmonga ko\'tariladi','Yerda qoladi'],2,'Doimiy intilishi tufayli Osmonga ko\'tariladi, Mefistofel yutqazadi.'),
    Q('Asos bo\'lgan afsona?', ['Antiq','O\'rta asr nemis','Yunon','Sharq'],1,'O\'rta asrlarda yashagan Doktor Faust afsonasiga asoslangan.'),
  ],
  'sherlock-holmes': [
    Q('Xolms va Uotson qayerda tanishadilar?', ['Kasalxonada','Beyker-strit 221B','Sudda','Jinoyat joyida'],1,'Beyker-strit 221B da xonani birga ijaraga olmoqchi bo\'lganlarida.'),
    Q('Xolms nima o\'ynaydi?', ['Pianino','Skripka','Gitara','Fleyta'],1,'Skripka - murakkab jinoyatlar haqida o\'ylayotganda chalar edi.'),
    Q('Xolmsning akasi?', ['Maykroft Xolms','Moriarti','Uotson','Lestred'],0,'Maykroft - Sherlokdan aqlli, ammo dangasa, Britaniya hukumati uchun ishlaydi.'),
    Q('Asosiy dushmani?', ['Lestred','Professor Moriarti','Uotson','Maykroft'],1,'Moriarti - jinoyat olamining dahosi, Reyxenbax sharsharasida halok bo\'ladi.'),
    Q('"Baskervillar iti"dagi maxluq?', ['Haqiqiy it','G\'ayritabiiy maxluq','Fosfor bilan surtilgan katta it','Bo\'ri'],2,'Fosfor bilan surtilib qorong\'ida yonadigan it.'),
    Q('Doktor Uotson kasbi?', ['Huquqshunos','Harbiy shifokor','Muhandis','Jurnalist'],1,'Sobiq harbiy shifokor, Afg\'onistonda yaralanib qaytgan.'),
    Q('Xolms qanday usul ishlatadi?', ['Sehrgarlik','Deduktiv metod','Tortura','So\'roq'],1,'Eng kichik detallarni kuzatib, mantiqiy xulosalar chiqaradi.'),
    Q('Reyxenbax sharsharasida kim bilan kurashadi?', ['Maykroft','Moriarti','Sebastian Moran','Lestred'],1,'Xolms va Moriarti sharsharaga qulab tushadi, Xolms tirik qoladi.'),
    Q('Konan Doyl millati?', ['Amerikalik','Shotlandiyalik','Fransuz','Nemis'],1,'Shotlandiyalik yozuvchi va shifokor.'),
    Q('Xolmsning xonadoni manzili?', ['Oksford-strit','Beyker-strit 221B','Pikkadilli','Tom strit'],1,'Beyker-strit 221B - eng mashhur adabiy manzillardan biri.'),
  ],
  'kichkina-shohzoda': [
    Q('Muallifi?', ['Peru Sent-Ekzyuperi','Antuan de Sent-Ekzyuperi','Jules Vern','Alber Kamyu'],1,'Fransuz yozuvchisi va uchuvchisi, 1943.'),
    Q('Qaysi sayyoradan?', ['Yer','Mars','B-612 asteroidi','Venera'],2,'B-612 asteroid sayyorasi.'),
    Q('Qanday gulni parvarish qiladi?', ['Lola','Atirgul','Binafsha','Liliya'],1,'Bir mag\'rur atirgulni.'),
    Q('Uchuvchi bilan qayerda uchrashadi?', ['Shaharda','Sahroi Kabirda','Dengizda','O\'rmonda'],1,'Samolyot qulagan Sahroi Kabirda.'),
    Q('Yerga kelishdan oldin nechta sayyoraga boradi?', ['3','5','6','7'],2,'6 ta sayyora, har birida turli kattalarni uchratadi.'),
    Q('Tulki qanday sir aytadi?', ['Boy bo\'lishni','"Faqat yurak bilan ko\'rasan"','Uchishni','Xazina joyini'],1,'"Eng muhim narsa ko\'zga ko\'rinmaydi" - asarning asosiy g\'oyasi.'),
    Q('Ilon ramzi?', ['Do\'stlik','Sevgi','O\'lim','Boylik'],2,'O\'lim va boshqa dunyoga o\'tishni ifodalaydi.'),
    Q('Chiroq yoquvchi kim?', ['Qirol','Mayor','Chiroqchi','Geograf'],2,'Har daqiqa chiroq yoqib-o\'chiruvchi, sayyorasida kun-tun tez almashadi.'),
    Q('Asar kimga bag\'ishlangan?', ['Onasiga','Do\'stiga','Leon Vertga','Otasiga'],2,'Leon Vertga, "axir hamma kattalar bir paytlar bolalar edi".'),
    Q('"Qo\'y" obrazi ma\'nosi?', ['Ovqat','Oddiy hayvon','Himoyaga muhtoj pokiza narsa','Yovvoyi hayvon'],2,'Pokiza va himoyaga muhtoj narsani ramziy ifodalaydi.'),
  ],
  'temur-tuzuklari': [
    Q('Asar muallifi kim?', ['Mirzo Ulug\'bek','Amir Temur','Ibn Xaldun','Sharafiddin Ali Yazdiy'],1,'Amir Temurning o\'zi tomonidan yozilgan davlat boshqaruvi va harbiy san\'at asari.'),
    Q('Asar necha bobdan iborat?', ['6','8','12','16'],2,'12 bob, davlat boshqaruvi, harbiy tuzilma, soliq va adolat haqida.'),
    Q('Davlat kengashi necha kishidan?', ['3','7','12','40'],2,'12 kishilik donishmandlar kengashi.'),
    Q('Muvaffaqiyat asosiy sababi?', ['Boylik','Adolat va tartib-intizom','Qo\'rqitish','Ayyorlik'],1,'Adolat, qat\'iy tartib-intizom va maslahatlashish.'),
    Q('Asar qaysi tilda?', ['Arab','Fors','Turkiy (Chig\'atoy)','Mo\'g\'ul'],2,'Turkiy tilning chig\'atoy lahjasida.'),
    Q('Lashkarboshilarga talab?', ['Boy bo\'lishi','Adolatli, jasur, tajribali','Yosh','Savodli'],1,'Adolatli, jasur va askarlarga g\'amxo\'r bo\'lishi kerak.'),
    Q('Soliq tamoyili?', ['Maksimal soliq','Xalq holiga qarab adolatli','Bekor qilish','Faqat boylardan'],1,'Xalqning iqtisodiy holatiga qarab adolatli soliq.'),
    Q('Elchilarga munosabat?', ['Qamash','Hurmat va izzat-ikrom','Kuzatmaslik','Gaplashmaslik'],1,'Elchilarni hurmat qilish va izzat-ikrom ko\'rsatish.'),
    Q('Asar qachon yozilgan?', ['1370','1405','1390','1420'],1,'Hayotining so\'nggi yillarida, taxminan 1405.'),
    Q('Asar janri?', ['She\'riy to\'plam','Tarixiy-huquqiy pandnoma','Romantik qissa','Ilmiy risola'],1,'Tarixiy-huquqiy pandnoma, davlat boshqaruvi va harbiy san\'at haqida qimmatli manba.'),
  ],
  'siyosatnoma': [
    Q('Muallifi?', ['Kaykovus','Amir Temur','Nizamulmulk','Sa\'diy Sheroziy'],2,'Saljuqiylar vaziri Nizamulmulk (Abu Ali Hasan at-Tusiy).'),
    Q('Nizamulmulk qaysi davlatda vazir?', ['Movarounnahr','Saljuqiylar','Hindiston','Misr'],1,'Saljuqiylar sultonlari Alp Arslon va Malikshoh davrida 30 yil vazir.'),
    Q('Asar necha bob?', ['20','50','11','39'],2,'11 bob (ba\'zi nusxalarda 50 bob).'),
    Q('Kimga bag\'ishlangan?', ['Alp Arslonga','Malikshohga','Xalifaga','O\'g\'liga'],1,'Sulton Malikshohga, davlat boshqaruvi bo\'yicha maslahatlar.'),
    Q('Hukmdor fazilatlari?', ['Boylik va hashamat','Adolat, donishmandlik','Qattiqqo\'llik','Dangasalik'],1,'Adolatli, donishmand, xalqiga g\'amxo\'r va ilmli.'),
    Q('Nizamulmulk qanday muassasalar asos solgan?', ['Kutubxonalar','Nizamiya madrasalari','Harbiy maktablar','Rasadxonalar'],1,'Bag\'dod, Nishapur, Isfahonda Nizamiya madrasalariga asos solgan.'),
    Q('Amaldorlarni tanlash tamoyili?', ['Faqat qarindoshlar','Loyiq va qobiliyatli','Boy kishilar','Tasodifiy'],1,'Loyiqligi, qobiliyati va halolligiga e\'tibor berish.'),
    Q('Asarning boshqa nomi?', ['Pandnoma','Siyar ul-muluk','Tuzuklar','Mulkdorlar'],1,'"Siyar ul-muluk" - Hukmdorlar yo\'li.'),
    Q('Josuslik tizimi?', ['Kerak emas','Doimiy josuslik bo\'lishi kerak','Faqat urushda','Gunoh'],1,'Davlat xavfsizligi uchun doimiy axborot to\'plash tizimi muhim.'),
    Q('Asar tili?', ['Arab','Fors','Turkiy','Mo\'g\'ul'],1,'Fors tilida yozilgan.'),
  ],
  'qobusnoma': [
    Q('Muallifi?', ['Nizamulmulk','Kaykovus','Firdavsiy','Sa\'diy Sheroziy'],1,'Ziyoriddin Abu Muhammad Kaykovus ibn Iskandar, Tabariston hukmdori.'),
    Q('Kimga bag\'ishlangan?', ['Sultonga','O\'g\'li Gilonshohga','Otasiga','Shogirdiga'],1,'O\'z o\'g\'li Gilonshohga pand-nasihat sifatida.'),
    Q('Necha bob?', ['25','34','44','50'],2,'44 bob, turli hayotiy maslahatlar.'),
    Q('Janri?', ['Tarixiy','Pandnoma','Romantik qissa','Ilmiy'],1,'Pandnoma (nasihatnoma) - otaning o\'g\'liga nasihatlari.'),
    Q('Yosh yigitga qanday kasb tavsiyasi?', ['Faqat savdogar','O\'z qobiliyatiga qarab hunar o\'rganish','Faqat dehqon','Faqat harbiy'],1,'O\'z qobiliyati va mayliga qarab hunar o\'rganish, chunki hunarli xor bo\'lmas.'),
    Q('Mehmondo\'stlik haqida?', ['Ochko\'zlik qilmaslik','Hurmat va izzat-ikrom','Pul talab qilish','Uzoq ushlab qolish'],1,'Mehmonni hurmat qilish va saxovatli bo\'lish.'),
    Q('Asar tili?', ['Arab','Fors','Turkiy','Mo\'g\'ul'],1,'Fors tilida, XI asr fors adabiyoti nodir yodgorligi.'),
    Q('Do\'st tanlash maslahati?', ['Ko\'p do\'st','Yaxshi do\'st tanlash','Hech kim bilan','Faqat boylar'],1,'Yaxshi va sodiq do\'st tanlash, yomon do\'stdan saqlanish.'),
    Q('Qachon yozilgan?', ['1000','1082','1120','950'],1,'1082 yilda.'),
    Q('O\'zbekcha tarjimoni?', ['Oybek','Muhammadjon Osim','Shuhrat Sirojiddinov','Xamid Sulaymon'],1,'Muhammadjon Osim va boshqa olimlar.'),
  ],
  guliston: [
    Q('Muallifi?', ['Umar Xayyom','Sa\'diy Sheroziy','Firdavsiy','Rumiy'],1,'Fors shoiri va mutafakkiri Sa\'diy Sheroziy.'),
    Q('Necha bob?', ['5','7','8','10'],2,'8 bob - podshohlar odobi, darveshlar axloqi, sabr va shukr.'),
    Q('Usuli?', ['Faqat she\'r','Faqat nasr','She\'r va nasr aralash','Faqat hikoya'],2,'Saj\' usulida nasr va she\'r aralash.'),
    Q('Sa\'diy qaysi asrda?', ['X','XI','XIII','XIV'],2,'1210-1291 (XIII asr).'),
    Q('1-bob mavzusi?', ['Sevgi','Podshohlar odobi','Do\'stlik','Ilm'],1,'"Podshohlar odobi" - adolatli hukmdor haqida.'),
    Q('Qabri qayerda?', ['Bag\'dod','Sheroz','Isfahon','Nishopur'],1,'Sherozda, "Sa\'diya" maqbarasi.'),
    Q('Yana bir mashhur asari?', ['Shohnoma','Bo\'ston','Masnaviy','Devon'],1,'"Bo\'ston" (1257) - Gulistondan bir yil oldin yozilgan.'),
    Q('Asar tili?', ['Arab','Turkiy','Fors','Mo\'g\'ul'],2,'Fors tilida.'),
    Q('Asosiy mavzu?', ['Harbiy san\'at','Tarix','Axloqiy tarbiya va insoniy fazilatlar','Astronomiya'],2,'Axloqiy tarbiya, insoniy fazilatlar, adolat va sabr.'),
    Q('Qachon yozilgan?', ['1158','1200','1258','1300'],2,'1258 (hijriy 656) yilda.'),
  ],
  'atom-odatlar': [
    Q('Muallifi?', ['Brayan Treysi','Jeyms Klir','Stiven Kovi','Robert Kiyosaki'],1,'Jeyms Klir - amerikalik yozuvchi va odatlar bo\'yicha mutaxassis.'),
    Q('1-qonun?', ['Jo\'lib ketish (Make it Obvious)','Qiziqarli qilish','Oson qilish','Qoniqarli qilish'],0,'Yaxshi odatlarni aniq va ko\'zga ko\'rinadigan qilish.'),
    Q('Nechta qonun?', ['3','4','5','7'],1,'4 ta qonun: Jo\'lib ketish, Qarshilik, Oson, Qoniqarli.'),
    Q('1% yaxshilanish natijasi?', ['37 baravar','2 baravar','10 baravar','Hech narsa'],0,'Har kuni 1% yaxshilanish 1 yilda 37 baravar (1.01^365 = 37.78).'),
    Q('Maqsaddan ko\'ra nima muhim?', ['Tizimlar (systems)','Pul','Vaqt','Talant'],0,'Maqsadga erishish emas, balki tizim yaratish muhim.'),
    Q('2-qonun mazmuni?', ['Yashirish','Yomon odatlarni ko\'zga ko\'rinmas qilish','Murakkablashtirish','Tashkil qilish'],1,'Yomon odatlarni invisible qilish (make it invisible).'),
    Q('Muhitning roli?', ['Muhim emas','Odatlarni shakllantirishda muhim','Faqat ishda','Kerak emas'],1,'Muhitni yaxshi odatlarga moslashtirish kerak.'),
    Q('3-qonun mazmuni?', ['Vaqtni ko\'paytirish','Odatni boshlashni osonlashtirish','Murakkablashtirish','Tashlab yuborish'],1,'Yaxshi odatni imkon qadar oson boshlash.'),
    Q('4-qonun mazmuni?', ['Yoqimsiz qilish','Ijobiy mukofot qo\'shish','Uzaytirish','Bekor qilish'],1,'Yaxshi odatni darhol qoniqish bilan bog\'lash.'),
    Q('Kitob qaysi yil nashr?', ['2016','2017','2018','2019'],2,'2018 yil 16 oktabr, tezda bestseller.'),
  ],
  qorqma: [
    Q('Muallifi?', ['Tohir Malik','Javlon Jovliyev','Akrom Malik','Said Ahmad'],1,'Zamonaviy o\'zbek yozuvchisi Javlon Jovliyev.'),
    Q('Qaysi davr tasvirlangan?', ['Mustaqillik','Sovet','1920-yillar Germaniyasi','Ikkinchi jahon urushi'],2,'Germaniyada o\'qigan o\'zbek jadid talabalarining taqdiri.'),
    Q('Asosiy mavzu?', ['Sevgi','Zulmga qarshi kurash va erkinlik','Sarguzasht','Boylik'],1,'Zulmga qarshi turish, erkinlik va qatag\'onga uchragan jadidlar.'),
    Q('Talabalar hayoti?', ['Boy','Og\'ir, ilmga intilish','Beparvo','Qiziqarli'],1,'Og\'ir sharoitda ochlik va qiyinchiliklarga qaramay ilm olish.'),
    Q('Zamonaviy muammo?', ['Ekologiya','Totalitar tuzum ta\'siri','Iqtisodiy inqiroz','Texnologiya'],1,'Sovet tuzumining inson taqdiriga ta\'siri.'),
    Q('Bosh qahramon?', ['Temur','Bobur','Navoiy','Diyorbek'],0,'Temur - orzular va haqiqat o\'rtasida ikkilanadi.'),
    Q('Nashr yili?', ['2018','2019','2020','2021'],2,'2020.'),
    Q('"Qo\'rqma" ma\'nosi?', ['Qo\'rqmaslik','Jasorat va qo\'rquvni yengish','Ehtiyotkorlik','Beparvolik'],1,'Qo\'rquvni yengish va qat\'iyat bilan oldinga intilish.'),
    Q('Jadid talabalar taqdiri?', ['Baxtli','Katag\'on qilinadi','Vatanga qaytadi','Germaniyada qoladi'],1,'Sovet tuzumi tomonidan qatag\'on qilinadi.'),
    Q('Javlon Jovliyev yo\'nalishi?', ['Tarixiy roman','Zamonaviy psixologik roman','Fantastika','Detektiv'],1,'Zamonaviy o\'zbek psixologik romani.'),
  ],
  molxona: [
    Q('Muallifi?', ['Jorj Oruell','Oldos Xaksli','Yevgeniy Zamyatin','Jon Shtaynbek'],0,'Ingliz yozuvchisi Jorj Oruell (Eric Arthur Blair).'),
    Q('Qo\'zg\'olonga chorlagan cho\'chqa?', ['Napoleon','Snowball','Mayor','Squealer'],2,'Keksa cho\'chqa Mayor barchani inson zulmiga qarshi qo\'zg\'olonga chorlaydi.'),
    Q('Asosiy tamoyil o\'zgarishi?', ['"Ba\'zi hayvonlar tengroq"','"Hech kim teng emas"','"Faqat cho\'chqalar teng"','"Hech qanday tenglik"'],0,'"Barcha hayvonlar teng, lekin ba\'zilari tengroq".'),
    Q('Boxer taqdiri?', ['Ot - sog\'lom','Ot - so\'yilishga sotiladi','Sigir','It'],1,'Kuchli ot, kasal bo\'lgach cho\'chqalar uni so\'yishga sotadi.'),
    Q('Qaysi voqeaga allegoriya?', ['Fransuz inqilobi','1917 inqilobi va Stalin davri','Amerika urushi','Ikkinchi jahon urushi'],1,'1917 Rossiya inqilobi va Stalin davri totalitarizmi.'),
    Q('Snowball va Napoleon ziddiyati?', ['Oziq-ovqat','Firma boshqaruvi va qarashlar','Ish hajmi','Yosh'],1,'Boshqaruv va kelajak rejalari farqi.'),
    Q('Squealer vazifasi?', ['Jangchi','Targ\'ibotchi','Oshpaz','Qo\'riqchi'],1,'Napoleonning noqonuniy harakatlarini mantiqiy asoslab beradi.'),
    Q('Asar oxiri?', ['Hayvonlar odamlarni quvadi','Hayvon va odam farqsiz','Cho\'chqalar odamga o\'xshab qoladi','Ferma buziladi'],2,'Cho\'chqalar ikki oyoqda, inson kiyimida - farq yo\'qolgan.'),
    Q('Nashr yili?', ['1940','1945','1949','1950'],1,'1945.'),
    Q('Asosiy g\'oya?', ['Hayvonlarni himoya','Hokimiyat korrupsiyasi va totalitarizm tanqidi','Qishloq xo\'jaligi','Oila qadriyatlari'],1,'Inqilobning liderlar tomonidan buzilishi va totalitarizm tanqidi.'),
  ],
  'orwell-1984': [
    Q('Bosh qahramon?', ['O\'Brayen','Uinston Smit','Juliya','Parsons'],1,'Uinston Smit - Okeaniyada Katta birodarga qarshi chiqadi.'),
    Q('Totalitar davlat nomi?', ['Okeaniya','Evroaziya','Pravda','Miniluv'],0,'Okeaniya, Katta birodar tomonidan boshqariladi.'),
    Q('"Katta birodar" kim?', ['Haqiqiy shaxs','Partiya rahbari ramziy obraz','Uinstonning otasi','Tarixiy shaxs'],1,'Suratlari hamma joyda "Katta birodar seni kuzatib turibdi" shiori bilan.'),
    Q('Uinston lavozimi?', ['Tergovchi','Haqiqat vazirligida xodim','Harbiy','Shifokor'],1,'Tarixni partiya talabiga moslab qayta yozadi.'),
    Q('Uchta shior?', ['"Tinchlik, Taraqqiyot, Insoniyat"','"Urush - tinchlik, Ozodlik - qullik, Bilimsizlik - kuch"','"Haqiqat, Adolat, Erkinlik"','"Ish, Oila, Vatan"'],1,'Partiyaning uch shiori.'),
    Q('Uinston va Yuliya yakuni?', ['Ajraladi','Qochadi','Qiynoqlardan so\'ng bir-biriga xiyonat qiladi','Baxtli yashaydi'],2,'101-xonada qiynoqlardan so\'ng bir-birlariga xiyonat qiladilar.'),
    Q('101-xona nima?', ['Yig\'ilish xonasi','Qiynoq xonasi','Uinston xonasi','Arxiv'],1,'Har kimning eng katta qo\'rquvi amalga oshiriladi.'),
    Q('O\'Brayen aslida kim?', ['Amerikalik josus','Partiya maxfiy agenti','Uinstonning do\'sti','Kuzatuvchi'],1,'Uinston va Yuliyani tuzoqqa tushiradi.'),
    Q('Newspeak maqsadi?', ['Chet til oson','Fikrlashni cheklash va isyonni oldini olish','Adabiyot rivoji','Ta\'lim'],1,'Lug\'atni cheklab, fikrlash doirasini cheklash.'),
    Q('Oxirgi jumla?', ['"U erkin edi"','"U Katta birodarni sevib qoldi"','"Hammasi tugadi"','"Uyg\'onish"'],1,'"He loved Big Brother" - Uinstonning to\'liq buzilganini anglatadi.'),
  ],
  alkimyogar: [
    Q('Muallifi?', ['Gabriel Garsia Markes','Paulo Koelo','Xorxe Luis Borxes','Mario Vargas Lyosa'],1,'Braziliyalik yozuvchi Paulo Koelo.'),
    Q('Santyago kasbi?', ['Savdogar','Cho\'pon (qo\'y boquvchi)','Olim','Harbiy'],1,'Andalusiyada qo\'ylarini boqadi.'),
    Q('"Shaxsiy afsona"ni tushuntirgan kim?', ['Qirolicha','Melkizedek','Rim papasi','Otasi'],1,'Melkizedek (Salim qiroli) yo\'l ko\'rsatadi.'),
    Q('Alkimyogar bilan uchrashuv?', ['Fatima','Melkizedek','Ingliz sayyohi','Al-Fayum alkimyogari'],3,'200 yoshli alkimyogar tabiat tillarini o\'rgatadi.'),
    Q('Piramidalardagi xazina?', ['Oltin','Hech narsa','O\'zi kelgan joyda daraxt tagida','Sehrli kitob'],2,'Xazina aslida Andalusiyadagi daraxt tagida ekanligini tushunadi.'),
    Q('Asosiy g\'oya?', ['Boylik','Orzularga ergashish va Shaxsiy afsona','Sayohat','Ilm'],1,'Orzularga ergashish, butun olam yordam beradi.'),
    Q('Afrikadagi muammo?', ['Kasallik','Ochlik','Pulini aldov bilan yo\'qotadi','Adashadi'],2,'Bir notanishga ishonib pullarini yo\'qotadi.'),
    Q('Santyago sevgan qiz?', ['Laylo','Zahro','Fatima','Oysha'],2,'Sahro vohasida Fatimani uchratadi va sevib qoladi.'),
    Q('"Olam ruhi" tushunchasi?', ['Diniy','Barcha narsaning bog\'liqligi va energiya','Sayyohlar ruhi','O\'liklar ruhi'],1,'Barcha narsani bog\'lab turuvchi kuch va energiya.'),
    Q('Paulo Koelo millati?', ['Ispan','Portugal','Braziliyalik','Argentina'],2,'Braziliyalik, Rio-de-Janeyroda tug\'ilgan.'),
  ],
  'sariq-devni-minib': [
    Q('Muallifi?', ['O\'tkir Hoshimov','Xudoyberdi To\'xtaboyev','Said Ahmad','Tohir Malik'],1,'Xudoyberdi To\'xtaboyev.'),
    Q('"Sariq dev" ramzi?', ['Haqiqiy dev','Avtobus','Katta it','Yomg\'ir'],1,'Avtobus - Hoshimjon va do\'stlari avtobuslarga yopishib shaharni kezadilar.'),
    Q('Hoshimjon xarakteri?', ['Tirishqoq','Dangasa va sho\'x, keyin o\'z xatosini tushunadi','Jiddiy','Qo\'rqoq'],1,'Dangasa va sho\'x, lekin oxirida ilm olishga qaror qiladi.'),
    Q('Sehrli qalpoqchani kim beradi?', ['Onasi','Otasi','Sehrgar chol (Mo\'jiza)','Do\'sti'],2,'Bir mo\'jizakor chol beradi, uni ko\'rinmas qiladi.'),
    Q('To\'xtaboyev janri?', ['Tarixiy roman','Bolalar adabiyoti (sarguzasht)','Detektiv','She\'r'],1,'Bolalar va o\'smirlar uchun sarguzasht qissalar.'),
    Q('Asar janri?', ['Fantastik roman','Sarguzasht-tarbiyaviy qissa','Tarixiy','Detektiv'],1,'Sarguzasht va tarbiyaviy qissa.'),
    Q('Hoshimjon qanday qiyinchiliklarni yengadi?', ['Urush','Ochlik','O\'qishdagi dangasalik va yomon odatlar','Tabiiy ofat'],2,'Dangasalik va sho\'xlikni yengib to\'g\'ri yo\'lga o\'tadi.'),
    Q('To\'xtaboyevning yana bir asari?', ['Ufq','Beshinchi qavatdagi besh qavat','Shaytanat','Oq kema'],1,'"Beshinchi qavatdagi besh qavat" va "Sehrli qalpoqcha".'),
    Q('Nashr yili?', ['1965','1968','1972','1975'],1,'1968.'),
    Q('"Sariq dev" ma\'nosi?', ['Qo\'rqinchli dev','Sariq avtobus','Sariq cho\'l','Sariq kiyimdagi odam'],1,'Toshkent ko\'chalaridagi sariq avtobuslar.'),
  ],
  ufq: [
    Q('Muallifi?', ['Odil Yoqubov','Said Ahmad','Pirimqul Qodirov','Tog\'ay Murod'],1,'Said Ahmad (Ahmadjon Husanov).'),
    Q('Necha jild?', ['2','3 (trilogiya)','4','5'],1,'3 jild: "Ufq", "Ufq sari", "Kelinlar qo\'zg\'oloni".'),
    Q('Qaysi davr?', ['XIX asr','XX asr boshi','Ikkinchi jahon urushi va undan keyin','Mustaqillik'],2,'Urush va mehnat frontidagi xalq hayoti.'),
    Q('Asosiy mavzu?', ['Shahar hayoti','Urush va mehnat frontidagi xalq jasorati','Sevgi','Ilm'],1,'Urush yillarida o\'zbek xalqining mehnat frontidagi jasorati.'),
    Q('Urushga ketgan yigit?', ['Otabek','Vali','Yo\'lchi','Naim'],1,'Vali - uning rafiqasi va oilasining urush davridagi hayoti.'),
    Q('Ijtimoiy muammo?', ['Ekologiya','Korrupsiya','Urush davridagi ayollar taqdiri','Ta\'lim'],2,'Ayollarning og\'ir hayoti, mehnat frontidagi jasorati.'),
    Q('Qahramon xarakteri ochilishi?', ['Monolog','Kundalik vaziyat va dialoglar','Tashqi ko\'rinish','She\'r'],1,'Jonli dialoglar va harakatlar orqali.'),
    Q('Nashr yili?', ['1964','1974','1984','1994'],1,'1974.'),
    Q('Bosh qahramon?', ['Zulfizaxon','Otabek','Miryoqub','Yo\'ldosh'],0,'Valining rafiqasi Zulfizaxon - oilani boshqaradi, og\'ir mehnat qiladi.'),
    Q('Said Ahmadga qanday shuhrat keltirgan?', ['Davlat mukofoti','Xalq yozuvchisi unvoni','O\'zbek adabiyoti durdonasi','Jahon tan olishi'],2,'O\'zbek adabiyotining sara asarlaridan biri.'),
  ],
  'otamdan-qolgan-dalalar': [
    Q('Muallifi?', ['Said Ahmad','Tog\'ay Murod','Pirimqul Qodirov','Odil Yoqubov'],1,'Tog\'ay Murod (Murod Tog\'aymurodov).'),
    Q('Bosh qahramon?', ['Dehqon - ota','Yo\'lchi','Otabek','Vali'],0,'Dehqon otaning obrazi orqali o\'zbek dehqonining taqdiri.'),
    Q('Mavzu?', ['Shahar hayoti','Dehqonchilik qismati va paxta yakka hokimligi','Sevgi','Ilm'],1,'Paxta yakka hokimligi davrida o\'zbek dehqonlarining hayoti.'),
    Q('Zamonaviy va an\'anaviy to\'qnashuvi?', ['Texnologiya','Qadriyatlar to\'qnashuvi va yer masalasi','Siyosat','Din'],1,'An\'anaviy dehqonchilik va sovet tuzumi talablari.'),
    Q('Tog\'ay Murod davri?', ['XIX asr','XX asr sovet davri','Mustaqillik','XVIII asr'],1,'Sovet davri ijodkori.'),
    Q('"Ota" obrazi ma\'nosi?', ['Haqiqiy ota','Oddiy dehqonning ramzi, vatan va meros','Qahramon','Boy'],1,'Dehqon mehnati, vatanga muhabbat va avlodlar merosi.'),
    Q('Asar uslubi?', ['She\'riy nasr','Sodda xalq tili va og\'zaki hikoya','Ilmiy','Fantastik'],1,'Xalq og\'zaki ijodi uslubida, sodda va ta\'sirli.'),
    Q('Qishloq hayoti jihatlari?', ['Bayramlar','Paxta maydonlari va mehnatkash xalq turmushi','Sport','Sayyohlik'],1,'Paxta dalalaridagi og\'ir mehnat va dehqonlar hayoti.'),
    Q('Tog\'ay Murod asarlari?', ['Ufq','Otamdan qolgan dalalar, Yulduzlar mangu yonadi','Shaytanat','Oq kema'],1,'"Otamdan qolgan dalalar" va "Yulduzlar mangu yonadi".'),
    Q('"Dalalar" ramziy ma\'nosi?', ['Go\'zal tabiat','Dehqon mehnati, Vatan, ota merosi','O\'simliklar','Yo\'llar'],1,'Ota merosi, vatan, avlodlar xotirasi.'),
  ],
  'oq-kema': [
    Q('Muallifi?', ['Chingiz Aytmatov','Tog\'ay Murod','Said Ahmad','Odil Yoqubov'],0,'Chingiz Aytmatov.'),
    Q('Bosh qahramon?', ['Chol','7 yoshli bolakay','Momun','Orozkul'],1,'Ismi aytilmagan 7 yoshli bolakay.'),
    Q('Qanday afsona aytiladi?', ['Oltin baliq','Shoxdor ona bug\'u','Uchar gilam','Oq ilon'],1,'Shoxdor ona bug\'u haqidagi afsona.'),
    Q('Asosiy konflikt?', ['Yaxshilik va yomonlik','Inson va tabiat','Kattalar vahshiyligi va bolaning pokizaligi','Urush'],2,'Bolakayning pokizaligi va kattalarning shafqatsizligi.'),
    Q('Momun xarakteri?', ['Qattiqqo\'l','Yumshoq va itoatkor chol','Jasur','Boy'],1,'Yumshoq, mehribon, biroq irodasiz chol.'),
    Q('Bolakayning orzusi?', ['Uchish','Oq kemada otasini ko\'rish','Boy bo\'lish','Shaharga borish'],1,'Issiqko\'ldagi oq kemada otasini ko\'rishni orzu qiladi.'),
    Q('Aytmatov tili?', ['Faqat rus','Rus va qirg\'iz tillarida','Faqat qirg\'iz','Faqat o\'zbek'],1,'Ikkala tilda ijod qilgan.'),
    Q('Tabiat tasviri?', ['Ikkinchi darajali','Asar markazida, go\'zal va ramziy','Muhim emas','Faqat fon'],1,'Tabiat - asar markazida, go\'zal va ramziy tasvirlar.'),
    Q('Asar oxiri?', ['Baxtli','Bolakay oq kemaga aylanadi','Bolakay o\'ladi','Kattalar o\'zgaradi'],1,'Bolakay baliqqa aylanib oq kema tomon suzadi (ramziy).'),
    Q('Asosiy g\'oya?', ['Tabiatni asrash','Insoniy pokizalik va yaxshilikning yovuzlik ustidan g\'alabasi','Do\'stlik','Sevgi'],1,'Inson qalbidagi pokizalik va afsonalarga ishonch.'),
  ],
  'boy-ota-kambagal-ota': [
    Q('Muallifi?', ['Brayan Treysi','Robert Kiyosaki','Stiven Kovi','Deyl Karnegi'],1,'Robert Kiyosaki.'),
    Q('Kambag\'al otasi qanday lavozimda?', ['Tadbirkor','Hukumat xodimi','Professor','Shifokor'],1,'Hukumat xodimi, yuqori maoshli ammo moliyaviy qiyin ahvolda.'),
    Q('"Boy ota"ga ko\'ra boylik kaliti?', ['Ko\'p ishlash','Aktivlar orttirish','Pul yig\'ish','Qarz olish'],1,'Aktivlar orttirish va ularni ko\'paytirish.'),
    Q('Aktiv va passiv farqi?', ['Farqi yo\'q','Aktiv - daromad keltiradi, passiv - olib ketadi','Aktiv - qimmat','Passiv - arzon'],1,'Aktiv pul keltiradi, passiv pulni olib ketadi.'),
    Q('Ish haqi uchun ishlashdan muhimi?', ['Ko\'proq ishlash','Aktivlar sotib olish','Qarz olish','Tejamkorlik'],1,'Aktivlar orttirish va ularni boshqarish.'),
    Q('Nechta moliyaviy dars?', ['3','5','6','10'],2,'6 ta asosiy moliyaviy dars.'),
    Q('Ko\'chmas mulk investitsiyasi?', ['Xavfli','Boylik yaratish vositasi','Murakkab','Keraksiz'],1,'Ko\'chmas mulk - aktivlar orttirishning samarali usuli.'),
    Q('Nashr yili?', ['1994','1997','2000','2002'],1,'1997.'),
    Q('Kiyosaki moliyaviy erkinlik yo\'li?', ['Tejash','Investitsiya va aktivlar orttirish','Qarz olmaslik','Ko\'p ishlash'],1,'Aktivlar orttirish, investitsiya qilish va passiv daromad yaratish.'),
    Q('Moliyaviy savodxonlik ta\'rifi?', ['Pulni saqlash','Pulni boshqarish va ishlatishni bilish','Kredit olish','Byudjet tuzish'],1,'Pulni qanday ishlab topish, boshqarish va ko\'paytirishni bilish.'),
  ],
  'samaradorlik-21': [
    Q('Muallifi?', ['Robert Kiyosaki','Brayan Treysi','Stiven Kovi','Kal Nyuport'],1,'Kanadalik-amerikalik muallif Brayan Treysi.'),
    Q('Nechta samaradorlik yo\'li?', ['7','10','21','50'],2,'21 ta samaradorlik yo\'li.'),
    Q('"Qurbaqani yeyish" g\'oyasi?', ['Kechasi ovqatlanish','Eng qiyin vazifani ertalab bajarish','Tez ovqatlanish','Sport'],1,'Eng muhim va qiyin vazifani kunning boshida bajarish.'),
    Q('Eng muhim vazifani aniqlash usuli?', ['Tasodifiy','ABCDE usuli - vazifalarni tartiblash','Eng yengil','Eng qiziqarli'],1,'ABCDE usuli - vazifalarni ahamiyati bo\'yicha tartiblash.'),
    Q('Vaqtni boshqarish usullari?', ['Multitasking','Rejalashtirish va ustuvorlik','Kutish','Tezlashtirish'],1,'Rejalashtirish, ustuvorlik belgilash va diqqatni jamlash.'),
    Q('Maqsad belgilash tizimi?', ['SMART maqsadlar','Tasodifiy','Kunlik','Oylik'],0,'Aniq, o\'lchanadigan, erishish mumkin, tegishli va vaqtli maqsadlar.'),
    Q('Kunlik rejalashtirish qoidasi?', ['80/20 qoidasi','50/50 qoidasi','10/90 qoidasi','30/70 qoidasi'],0,'Pareto qoidasi - 20% harakat 80% natija beradi.'),
    Q('Delegatsiya qilish haqida?', ['Muhim emas','Vaqtni bo\'shatish va boshqalarga ishonish','Faqat ishni bajarish','Keraksiz'],1,'Vaqtni muhim ishlarga ajratish uchun delegatsiya qilish.'),
    Q('Asosiy tamoyil?', ['Ko\'p ishlash','Aqlli ishlash va diqqatni jamlash','Tez ishlash','Kech qolish'],1,'Aqlli ishlash, muhim vazifalarga diqqatni jamlash.'),
    Q('Brayan Treysi sohasi?', ['Moliya','Shaxsiy samaradorlik va biznes','Tibbiyot','Texnologiya'],1,'Shaxsiy samaradorlik va biznes bo\'yicha mutaxassis.'),
  ],
  'diqqat-deep-work': [
    Q('Muallifi?', ['Brayan Treysi','Kal Nyuport','Jeyms Klir','Stiven Kovi'],1,'Kal Nyuport - amerikalik kompyuter olimi va yozuvchi.'),
    Q('"Chuqur ish" ta\'rifi?', ['Ko\'p ishlash','Chalg\'imasdan yuqori diqqat talab qiladigan ish','Tez ishlash','Jamoaviy ish'],1,'Chalg\'imasdan, yuqori kognitiv talab qiladigan ish.'),
    Q('"Sayoz ish" ta\'rifi?', ['Muhim ish','Diqqat talab qilmaydigan ishlar','Qiyin ish','Ijodiy ish'],1,'Elektron pochta, yig\'ilishlar kabi diqqat talab qilmaydigan ishlar.'),
    Q('Chuqur ishni rejalashtirish usuli?', ['Tasodifiy','Monastir, Bimodal, Ritmik, Jurnalist usullari','Faqat ertalab','Faqat kechqurun'],1,'4 usul: monastir, bimodal, ritmik va jurnalist usuli.'),
    Q('Ijtimoiy tarmoqlar maslahati?', ['Ko\'p ishlatish','Cheklash yoki butunlay voz kechish','Faqat ish uchun','Befarq'],1,'Chuqur ish uchun ijtimoiy tarmoqlarni cheklash.'),
    Q('Kal Nyuport kasbi?', ['Psixolog','Kompyuter olimi (professor)','Menejer','Doktor'],1,'Jorjtaun universitetida kompyuter fanlari professori.'),
    Q('Diqqatni jamlash qanday rivojlantiriladi?', ['Genetik','Mashq va odat orqali','Dori bilan','O\'qish orqali'],1,'Muntazam mashq va "chuqur ish" odati orqali.'),
    Q('Asosiy xulosa?', ['Ko\'p ishlash','Chuqur ish qobiliyati zamonaviy iqtisodiyotda eng muhim mahorat','Texnologiya muhim','Yolg\'iz ishlash'],1,'Chuqur ish qobiliyati - zamonaviy dunyoda eng qimmatli mahorat.'),
    Q('Nashr yili?', ['2014','2015','2016','2017'],2,'2016.'),
    Q('"Motorli ko\'nikmalar" bog\'liqligi?', ['Farqi yo\'q','Chuqur ish ham motorli ko\'nikma kabi mashq talab qiladi','Motorli ko\'nikmalar muhim emas','Faqat aqliy'],1,'Chuqur diqqat mushak kabi mashq qilish bilan rivojlanadi.'),
  ],
  halqa: [
    Q('Muallifi?', ['Tohir Malik','Akrom Malik','Javlon Jovliyev','Said Ahmad'],1,'Akrom Malik.'),
    Q('Asar janri?', ['Detektiv','Qissa (badiiy)','Fantastika','Tarixiy'],1,'Badiiy qissa.'),
    Q('Bosh qahramon?', ['Temur','Ruslan','Imon va nafs kurashidagi inson','Anvar'],2,'Inson qalbidagi imon va nafs kurashi.'),
    Q('Asosiy mavzu?', ['Detektiv','Iymon va nafs kurashi, ruhiy uyg\'onish','Sarguzasht','Sevgi'],1,'Imon va nafs kurashi, insoniy fazilatlar va ruhiy iztiroblar.'),
    Q('Zamonaviy jamiyat muammolari?', ['Ekologiya','Ma\'naviy tanazzul va ruhiy bo\'shliq','Iqtisodiyot','Siyosat'],1,'Zamonaviy jamiyatdagi ma\'naviy inqiroz.'),
    Q('Akrom Malik yo\'nalishi?', ['Tarixiy','Ma\'naviy-ruhiy va badiiy','Ilmiy','Fantastik'],1,'Ma\'naviy-ruhiy va badiiy yo\'nalish.'),
    Q('Nashr yili?', ['2017','2018','2019','2020'],2,'2019.'),
    Q('"Halqa" ma\'nosi?', ['Doira','Taqdir, inson hayotidagi davr va sinovlar','Zanjir','Hokimiyat'],1,'Taqdir, hayot davrlari va sinovlar.'),
    Q('Asarning o\'ziga xosligi?', ['Detektiv sarguzasht','Chuqur ruhiy tahlil va ma\'naviy mavzular','Tarixiy voqealar','Fantastik elementlar'],1,'Chuqur ruhiy tahlil va ma\'naviy mavzular.'),
    Q('Akrom Malik asarlari?', ['Shaytanat','Halqa, Yo\'l','Ufq','Oq kema'],1,'"Halqa", "Yo\'l" va boshqa ma\'naviy asarlar.'),
  ],
  shaytanat: [
    Q('Muallifi?', ['Akrom Malik','Tohir Malik','Javlon Jovliyev','Said Ahmad'],1,'Tohir Malik - o\'zbek adabiyotida detektiv janr asoschisi.'),
    Q('Necha jild?', ['2 jild','4 jild','6 jild','8 jild'],1,'4 jild.'),
    Q('Bosh qahramon?', ['Ruslan','Temur','Anvar','Otabek'],0,'Ruslan - jinoyat olami va adolat o\'rtasidagi kurashda.'),
    Q('Janri?', ['Sevgi romani','Detektiv roman','Tarixiy roman','Fantastika'],1,'O\'zbek detektiv romani.'),
    Q('Jinoyat olami tasviri?', ['Yorqin va jozibali','Shafqatsiz va realistik','Kulgili','Romantik'],1,'O\'zbek mafiyasi va jinoyatchilar dunyosi realistik tasvirlangan.'),
    Q('Ruslan xarakteri?', ['Oddiy inson','Murakkab, ziddiyatli shaxs','Qahramon','Yovuz'],1,'Murakkab va ziddiyatli shaxs, jinoyat va adolat oralig\'ida.'),
    Q('Tohir Malik davri?', ['1960','1970-1980','1990','2000'],2,'1994 yilda nashr etilgan.'),
    Q('Adolat va qonun mavzusi?', ['Ikkinchi darajali','Asosiy mavzulardan biri','Muhim emas','Faqat siyosat'],1,'Jinoyat va jazo, adolat va qonun ustuvorligi.'),
    Q('O\'zbek adabiyotidagi o\'rni?', ['Oddiy asar','Eng mashhur o\'zbek detektivi','Birinchi roman','So\'nggi asar'],1,'Eng mashhur o\'zbek detektiv asari.'),
    Q('Tohir Malikning yana bir asari?', ['Ufq','Baxt ko\'chasi','Oq kema','Halqa'],1,'"Baxt ko\'chasi" va boshqa asarlar.'),
  ],
  'saodat-asri': [
    Q('Muallifi?', ['Imom Buxoriy','Ahmad Lutfiy Qozonchi','Imom Gazzoliy','Rabg\'uziy'],1,'Ahmad Lutfiy Qozonchi.'),
    Q('Qaysi davr haqida?', ['Hozirgi zamon','Islomning ilk davrlari va Muhammad (s.a.v.) hayoti','XX asr','O\'rta asrlar'],1,'Islom olami tarixi va Muhammad (s.a.v.) hayoti.'),
    Q('Asosiy maqsad?', ['Tarix o\'rgatish','Islom tarixi va sahobalar hayotini ta\'sirli bayon qilish','Sayyohlik','Sarguzasht'],1,'Islom tarixi va Muhammad (s.a.v.) hayot yo\'lini jonli tasvirlash.'),
    Q('Sahobalar hayoti?', ['Qisqa','Ta\'sirli va batafsil yoritilgan','Muhim emas','Salbiy'],1,'Sahobalarning hayoti va ularning Islomdagi roli batafsil yoritilgan.'),
    Q('Ahmad Lutfiy Qozonchi millati?', ['O\'zbek','Arab (Misrlik)','Fors','Turk'],1,'Misrlik arab yozuvchisi.'),
    Q('Asar tili?', ['Fors','Arab','Turkiy','Urdu'],1,'Arab tilida yozilgan.'),
    Q('O\'zbekcha tarjimoni?', ['Oybek','Shuhrat Sirojiddinov','Pirimqul Qodirov','Odil Yoqubov'],1,'Shuhrat Sirojiddinov va boshqa tarjimonlar.'),
    Q('Eng ko\'p mavzu?', ['Sevgi','Iymon, sabr-toqat va Islomiy qadriyatlar','Boylik','Siyosat'],1,'Iymon, sabr-toqat va Islomiy qadriyatlar.'),
    Q('Nashr yili?', ['1995','1997','1999','2001'],2,'1999.'),
    Q('Uslubi?', ['Ilmiy','Badiiy va ta\'sirli, jonli hikoya uslubi','She\'riy','Detektiv'],1,'Jonli, ta\'sirli badiiy hikoya uslubi.'),
  ],
  'muvaffaqiyat-7': [
    Q('Muallifi?', ['Jeyms Klir','Stiven Kovi','Brayan Treysi','Robert Kiyosaki'],1,'Stiven R. Kovi.'),
    Q('1-ko\'nikma?', ['Maqsad qo\'yish','Faol bo\'lish (Be Proactive)','Rejalashtirish','Ishlash'],1,'"Faol bo\'lish" - o\'z hayoting uchun mas\'uliyat olish.'),
    Q('"Boshidan oxirni tasavvur qil" qaysi?', ['1-ko\'nikma','2-ko\'nikma','3-ko\'nikma','7-ko\'nikma'],1,'2-ko\'nikma - maqsadni aniq belgilash.'),
    Q('"G\'alaba-g\'alaba" mazmuni?', ['Raqobat','Ikkala tomon foyda ko\'radigan yechim','Yutqazish','Kurash'],1,'Hamkorlikda ikkala tomon manfaatini ko\'zlovchi yechim topish.'),
    Q('"Avval tushun, keyin tushunil" qaysi?', ['4','5','6','7'],1,'5-ko\'nikma - samarali muloqot siri.'),
    Q('"Arrani charxla" mazmuni?', ['Asbob tuzatish','Doimiy o\'z-o\'zini rivojlantirish va yangilash','Ishni to\'xtatish','Dam olish'],1,'Jismoniy, ruhiy, aqliy va ijtimoiy jihatdan doimiy rivojlanish.'),
    Q('"Faol bo\'lish" mazmuni?', ['Harakat qilish','Reaksiya emas, balki tanlov asosida harakat','Shoshilish','Gapirish'],1,'Vaziyatga qarab reaksiya emas, qadriyatlar asosida harakat qilish.'),
    Q('Ko\'nikmalar necha guruh?', ['2','3','4','5'],1,'3 guruh: xususiy g\'alaba (1-3), jamoa g\'alabasi (4-6), yangilanish (7).'),
    Q('Nashr yili?', ['1987','1988','1989','1990'],2,'1989.'),
    Q('Stiven Kovi sohasi?', ['Moliya','Shaxsiy rivojlanish va liderlik','Tibbiyot','Texnologiya'],1,'Shaxsiy rivojlanish va liderlik bo\'yicha mutaxassis.'),
  ],
};
const esc = s => s.replace(/'/g, "\\'");
const lines = ['['];
let first = true;
for (const [bid, qs] of Object.entries(BQ)) {
  qs.forEach((q, i) => {
    if (!first) lines[lines.length-1] += ',';
    first = false;
    lines.push('');
    lines.push('  {');
    lines.push(`    id: 'q-${bid}-${i+1}',`);
    lines.push(`    bookId: '${bid}',`);
    lines.push(`    question: '${esc(q.q)}',`);
    lines.push(`    options: [${q.o.map(o => `'${esc(o)}'`).join(', ')}],`);
    lines.push(`    correctAnswer: ${q.c},`);
    lines.push(`    explanation: '${esc(q.e)}'`);
    lines.push('  }');
  });
}
lines.push('');
lines.push(']');
require('fs').writeFileSync(
  'C:\\Users\\Hp\\.gemini\\antigravity\\scratch\\kitob-test\\scratch\\generated.js',
  lines.join('\n'),
  'utf8'
);
console.log('Done: ' + Object.values(BQ).reduce((a,b) => a + b.length, 0) + ' questions');
