[
  {    id: 'q-hamlet-1',    bookId: 'hamlet',    question: '"Hamlet" tragediyasida qirol Klavdiy Hamletga nisbatan kim bo\'ladi?',    options: ['Amakisi', 'Otasi', 'Akasi', 'Buvasi'],    correctAnswer: 0,    explanation: 'Klavdiy Hamletning amakisi bo\'lib, u Hamletning otasini o\'ldirib, taxt va qirolichaga ega chiqadi.'  },
  {    id: 'q-hamlet-2',    bookId: 'hamlet',    question: 'Hamlet mashhur "Yoki bo\'lmoq, yoki bo\'lmaslik" monologini qayerda aytadi?',    options: ['Qasr devorida', 'Qabristonda', 'Saroy zalida', 'Onasining xonasida'],    correctAnswer: 1,    explanation: 'Hamlet bu monologni qabristonda, bosh suyagiga qarab hayot va o\'lim haqida mulohaza yuritayotganda aytadi.'  },
  {    id: 'q-hamlet-3',    bookId: 'hamlet',    question: 'Hamlet sevgan qiz Poloniyning qizi kim edi?',    options: ['Ofeliya', 'Gertruda', 'Yorik', 'Yuliy'],    correctAnswer: 0,    explanation: 'Ofeliya - Poloniyning qizi va Hamletning sevgilisi. U Hamletning aqldan ozganligi va otasining o\'limidan keyin aqldan ozadi.'  },
  {    id: 'q-hamlet-4',    bookId: 'hamlet',    question: 'Hamlet asarida "spektakl ichida spektakl" sahnasining maqsadi nima?',    options: ['Shohona tomosha qilish', 'Klavdiyning aybini fosh etish', 'Ofeliyani sevish', 'Aqldan ozganlikni ko\'rsatish'],    correctAnswer: 1,    explanation: 'Hamlet aktyorlar yordamida otasining o\'ldirilishi sahnalashtirilgan spektaklni qo\'yib, Klavdiyning reaksiyasini kuzatadi.'  },
  {    id: 'q-hamlet-5',    bookId: 'hamlet',    question: 'Hamletning eng yaqin do\'sti va ishonchli maslahatchisi kim edi?',    options: ['Rozenkrans', 'Gildenstern', 'Horatsiy', 'Laert'],    correctAnswer: 2,    explanation: 'Horatsiy Hamletning eng sodiq do\'sti bo\'lib, u asar oxirida tirik qoladi va voqeani hikoya qiladi.'  },
  {    id: 'q-hamlet-6',    bookId: 'hamlet',    question: '"Hamlet" tragediyasining asosiy mavzusi nima?',    options: ['Sevgi va sadoqat', 'Qasos va ikkilanish', 'Boylik va hokimiyat', 'Do\'stlik va xiyonat'],    correctAnswer: 1,    explanation: 'Asarning asosiy mavzusi - qasos va ikkilanish, Hamlet otasining o\'limi uchun qasos olishda doimiy ikkilanadi.'  },
  {    id: 'q-hamlet-7',    bookId: 'hamlet',    question: 'Ofeliyaning o\'limi qanday tasvirlanadi?',    options: ['Qilich bilan o\'ldiriladi', 'Zahar ichadi', 'Daryoga cho\'kib ketadi', 'Saroy devoridan yiqiladi'],    correctAnswer: 2,    explanation: 'Ofeliya aqldan ozgan holda daryo bo\'yida gulchambarlar to\'qib yurganida, shox sinib, suvga tushib cho\'kadi.'  },
  {    id: 'q-hamlet-8',    bookId: 'hamlet',    question: 'Hamlet otasining sharpasini birinchi marta qayerda ko\'radi?',    options: ['Saroyda', 'Qasr devori ustida', 'Qabristonda', 'O\'rmonda'],    correctAnswer: 1,    explanation: 'Qirolning sharpasi birinchi marta qasr devori ustida, tungi soqchilarga ko\'rinadi.'  },
  {    id: 'q-hamlet-9',    bookId: 'hamlet',    question: 'Qirolicha Gertruda kimga turmushga chiqadi?',    options: ['Hamletning otasiga', 'Klavdiyga', 'Poloniyga', 'Laertga'],    correctAnswer: 1,    explanation: 'Gertruda - Hamletning onasi, eri vafot etgach, uning ukasi Klavdiyga turmushga chiqadi.'  },
  {    id: 'q-hamlet-10',    bookId: 'hamlet',    question: 'Asar oxirida qanday voqea yuz beradi?',    options: ['Hamlet qirol bo\'ladi', 'Hamlet va uning dushmanlari halok bo\'ladi', 'Hamlet Ofeliyaga uylanadi', 'Hamlet Angliyaga ketadi'],    correctAnswer: 1,    explanation: 'Asar oxirida qilichboslik paytida zaharli qilich va sharob tufayli Gertruda, Laert, Klavdiy va Hamletning o\'zi ham halok bo\'ladi.'  }
]